export const TIBIA_FANDOM_BATCH_3 = [
  {
    name: "Goshnar's Hatred",
    slug: "Goshnar's-Hatred",
    imageUrl: 'https://static.tibia.com/images/library/creatures/goshnarshatred.gif',
    boss: true,
    shortDescription:
      'Upiorny archfoe z Soul War skupiony na czystej wytrzymalosci i dlugiej walce w ciasnej arenie.',
    accessQuest: 'Wymaga dostepu do Soul War Quest.',
    location: 'Rotten Wasteland.',
    soloLevel: '1000+',
    groupLevel: '600+',
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
      drown: 0,
      lifedrain: 0,
    },
    loot: [
      { name: 'Ultimate Mana Potion', chance: 'common' },
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Figurine of Hatred', chance: 'uncommon' },
      { name: 'Vial of Hatred', chance: 'uncommon' },
      { name: 'Bracelet of Strengthening', chance: 'rare' },
      { name: 'Bag You Desire', chance: 'rare' },
      { name: 'Spectral Horse Tack', chance: 'very rare' },
    ],
  },
  {
    name: "Goshnar's Malice",
    slug: "Goshnar's-Malice",
    imageUrl: 'https://static.tibia.com/images/library/creatures/goshnarsmalice.gif',
    boss: true,
    shortDescription:
      'Lodowy archfoe z Soul War, ktory odbija zywiolowe obrazenia i potrafi mocno karac za zly element ataku.',
    accessQuest: 'Wymaga dostepu do Soul War Quest.',
    location: 'Claustrophobic Inferno.',
    soloLevel: '1000+',
    groupLevel: '600+',
    attackStyle: ['mocne ataki ice', 'odbicie obrazen zywiolowych', 'ice beamy', 'krwawe bomby'],
    resistances: {
      physical: 0,
      earth: -30,
      fire: -30,
      ice: 0,
      energy: -30,
      holy: 0,
      death: 0,
      drown: 0,
      lifedrain: 0,
    },
    loot: [
      { name: 'Ultimate Mana Potion', chance: 'common' },
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'Figurine of Malice', chance: 'uncommon' },
      { name: "Malice's Horn", chance: 'uncommon' },
      { name: "Malice's Spine", chance: 'uncommon' },
      { name: 'The Skull of a Beast', chance: 'semi-rare' },
      { name: 'Dragon Figurine', chance: 'rare' },
      { name: 'Spectral Saddle', chance: 'very rare' },
    ],
  },
  {
    name: "Goshnar's Spite",
    slug: "Goshnar's-Spite",
    imageUrl: 'https://static.tibia.com/images/library/creatures/goshnarsspite.gif',
    boss: true,
    shortDescription:
      'Soul Warowy archfoe bazujacy na energii, earth i life drainie, grozny zwlaszcza dla zle ustawionej druzyny.',
    accessQuest: 'Wymaga dostepu do Soul War Quest.',
    location: 'Ebb and Flow.',
    soloLevel: '1000+',
    groupLevel: '600+',
    attackStyle: ['fale energy', 'beam earth', 'life drain wave', 'mocne obrazenia fizyczne'],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
      drown: 0,
      lifedrain: 0,
    },
    loot: [
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'Ultimate Mana Potion', chance: 'common' },
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Figurine of Spite', chance: 'uncommon' },
      { name: "Spite's Spirit", chance: 'uncommon' },
      { name: 'The Skull of a Beast', chance: 'semi-rare' },
      { name: 'Bag You Desire', chance: 'rare' },
      { name: 'Spectral Horseshoe', chance: 'very rare' },
    ],
  },
  {
    name: 'Grand Master Oberon',
    slug: 'Grand-Master-Oberon',
    imageUrl: 'https://static.tibia.com/images/library/creatures/grandmasteroberon.gif',
    boss: true,
    shortDescription:
      'Lider Order of the Falcon z wyrazna mechanika debat i resetowania zycia przy niskim hp.',
    accessQuest: 'Czesc The Secret Library Quest i wejscie do Falcon Bastion.',
    location: 'Falcon Bastion.',
    soloLevel: '500+',
    groupLevel: '300+',
    attackStyle: [
      'mocne uderzenia wrecz',
      'holy beam',
      'groundshaker earth',
      'death strike i leczenie z debata',
    ],
    resistances: {
      physical: -30,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 25,
      death: -75,
      drown: 0,
      lifedrain: 0,
    },
    loot: [
      { name: 'The Spatial Warp Almanac', chance: 'very common' },
      { name: 'Falcon Bow', chance: 'rare' },
      { name: 'Falcon Shield', chance: 'rare' },
      { name: 'Falcon Plate', chance: 'very rare' },
      { name: 'Falcon Greaves', chance: 'very rare' },
      { name: 'Falcon Longsword', chance: 'rare' },
      { name: 'Falcon Coif', chance: 'rare' },
      { name: 'Grant of Arms', chance: 'semi-rare' },
    ],
  },
  {
    name: 'Ice Horror',
    slug: 'Ice-Horror',
    imageUrl: 'https://static.tibia.com/images/library/creatures/icehorror.gif',
    boss: true,
    shortDescription:
      'Nowoczesny boss z Okolnir oparty o burst energy i death, z lodowa odpornoscia i questowym cooldown resetem.',
    accessQuest:
      'Czesc The Roost of the Graveborn Quest; cooldown mozna resetowac Icy Horns, a Icy Crypt Rune wypada dopiero po ukonczeniu questa.',
    location: 'Okolnir.',
    soloLevel: '1000+',
    groupLevel: '600+',
    attackStyle: ['uderzenia wrecz', 'death ring', 'szeroka fala energy', 'presja obszarowa'],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: -100,
      energy: 0,
      holy: 0,
      death: 0,
      drown: 0,
      lifedrain: 0,
    },
    loot: [
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'Great Spirit Potion', chance: 'common' },
      { name: 'Ice Rapier', chance: 'common' },
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Frosty Heart', chance: 'common' },
      { name: 'Crystal Ring', chance: 'uncommon' },
      { name: 'Pair of Earmuffs', chance: 'uncommon' },
      { name: 'Icy Crypt Rune', chance: 'rare' },
    ],
  },
  {
    name: 'Ichgahal',
    slug: 'Ichgahal',
    imageUrl: 'https://static.tibia.com/images/library/creatures/ichgahal.gif',
    boss: true,
    shortDescription:
      'Jeden z najciezszych bossow Rotten Blood, z ogromnym hp, przywolaniami i bardzo mocnym death ringiem.',
    accessQuest: 'Jeden z bossow Rotten Blood Quest.',
    location: 'Putrefactory.',
    soloLevel: '1200+',
    groupLevel: '700+',
    attackStyle: [
      'mocne uderzenia wrecz',
      'great death ring',
      'agony beam',
      'mana drain i summon grzybow',
    ],
    resistances: {
      physical: 0,
      earth: -75,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
      drown: 0,
      lifedrain: 0,
    },
    loot: [
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Ultimate Spirit Potion', chance: 'common' },
      { name: 'Ultimate Mana Potion', chance: 'common' },
      { name: 'The Essence of Ichgahal', chance: 'uncommon' },
      { name: "Ichgahal's Fungal Infestation", chance: 'rare' },
      { name: 'Putrefactive Figurine', chance: 'rare' },
      { name: 'Spiritual Horseshoe', chance: 'very rare' },
    ],
  },
  {
    name: 'Irgix The Flimsy',
    slug: 'Irgix-The-Flimsy',
    imageUrl: 'https://static.tibia.com/images/library/creatures/irgix.gif',
    boss: true,
    shortDescription:
      'Widmowy boss z Feaster of Souls, prostszy mechanicznie, ale mocno niewrazliwy na energy i death.',
    accessQuest: 'Czesc Feaster of Souls Quest.',
    location: 'Netherworld.',
    soloLevel: '900+',
    groupLevel: '500+',
    attackStyle: ['walka wrecz'],
    resistances: {
      physical: -75,
      earth: 0,
      fire: 0,
      ice: 25,
      energy: -100,
      holy: 0,
      death: -100,
      drown: 0,
      lifedrain: 0,
    },
    loot: [
      { name: 'Skull Coin', chance: 'common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Diamond', chance: 'common' },
      { name: 'Silver Hand Mirror', chance: 'uncommon' },
      { name: 'Death Toll', chance: 'rare' },
      { name: 'Pair of Nightmare Boots', chance: 'rare' },
      { name: 'Glacial Rod', chance: 'semi-rare' },
      { name: 'Springsprout Rod', chance: 'semi-rare' },
    ],
  },
  {
    name: 'Katex Blood Tongue',
    slug: 'Katex-Blood-Tongue',
    imageUrl: 'https://static.tibia.com/images/library/creatures/katex.gif',
    boss: true,
    shortDescription:
      'Werehyaenowy boss z Lion Sanctum, niepozorny na papierze, ale grozny przez summon i szybkie kombo death plus earth.',
    accessQuest: 'Czesc Grimvale Quest, etap An Ancient Feud.',
    location: 'Lion Sanctum.',
    soloLevel: '250+',
    groupLevel: '180+',
    attackStyle: [
      'uderzenia wrecz',
      'death bomb i death wave',
      'earth hit',
      'przywolanie werehyaeny',
    ],
    resistances: {
      physical: 0,
      earth: -75,
      fire: -30,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
      drown: 0,
      lifedrain: 0,
    },
    loot: [
      { name: "Katex' Blood", chance: 'uncommon' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Ultimate Health Potion', chance: 'common' },
      { name: 'Werehyaena Nose', chance: 'common' },
      { name: 'Werehyaena Talisman', chance: 'uncommon' },
      { name: 'Werehyaena Trophy', chance: 'semi-rare' },
      { name: 'Magic Plate Armor', chance: 'rare' },
      { name: 'Ornate Crossbow', chance: 'rare' },
    ],
  },
  {
    name: 'King Zelos',
    slug: 'King-Zelos',
    imageUrl: 'https://static.tibia.com/images/library/creatures/kingzelos.gif',
    boss: true,
    shortDescription:
      'Final Grave Danger, byly krol Thais oparty na death obrazeniach, hexie i skalowaniu trudnosci zaleznie od postepu druzyny.',
    accessQuest: 'Finalny boss Grave Danger Quest po pokonaniu czterech minibossow.',
    location: 'Isle of the Kings.',
    soloLevel: '1000+',
    groupLevel: '500+',
    attackStyle: [
      'mocne uderzenia wrecz',
      'great hex beam',
      'rozszerzajacy sie death ring',
      'przywolania risen soldierow',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: -100,
      drown: 0,
      lifedrain: 0,
    },
    loot: [
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'Silver Token', chance: 'common' },
      { name: 'Gold Token', chance: 'uncommon' },
      { name: 'Ultimate Spirit Potion', chance: 'common' },
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Galea Mortis', chance: 'rare' },
      { name: 'Bow of Cataclysm', chance: 'rare' },
      { name: 'Death Oyoroi', chance: 'very rare' },
    ],
  },
  {
    name: 'Kusuma',
    slug: 'Kusuma',
    imageUrl: 'https://static.tibia.com/images/library/creatures/kusuma.gif',
    boss: true,
    shortDescription:
      "Asuryjski boss z Marapur, mobilny i wygodny do kite'owania dzieki unikaniu energy fieldow.",
    accessQuest: 'Dostep do areny przez Energy Vein na Marapur.',
    location: 'Marapur.',
    soloLevel: '250+',
    groupLevel: '180+',
    attackStyle: ['uderzenia wrecz', 'earth damage', 'death damage', 'samoleczenie'],
    resistances: {
      physical: 0,
      earth: -100,
      fire: 25,
      ice: 0,
      energy: 25,
      holy: -30,
      death: 0,
    },
    loot: [
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Leaf Star', chance: 'common' },
      { name: 'Gold Ingot', chance: 'uncommon' },
      { name: 'Soul Orb', chance: 'uncommon' },
      { name: 'Golden Lotus Brooch', chance: 'semi-rare' },
      { name: 'Terra Hood', chance: 'semi-rare' },
      { name: 'Terra Legs', chance: 'rare' },
      { name: 'Snakebite Rod', chance: 'rare' },
    ],
  },
  {
    name: 'Lady Tenebris',
    slug: 'Lady-Tenebris',
    imageUrl: 'https://static.tibia.com/images/library/creatures/ladytenebris.gif',
    boss: true,
    shortDescription:
      'Boss Forgotten Knowledge skupiony na death obrazeniach i groznej eksplozji po teleportowaniu graczy do srodka areny.',
    accessQuest: 'Jeden z bossow Forgotten Knowledge Quest.',
    location: 'Dungeon za Death Portalem i Old Masonry.',
    soloLevel: '500+',
    groupLevel: '300+',
    attackStyle: [
      'mocne uderzenia wrecz',
      'death beam',
      'death strike',
      'teleport do centrum i eksplozja',
    ],
    resistances: {
      physical: 0,
      earth: -30,
      fire: -30,
      ice: -30,
      energy: -30,
      holy: 0,
      death: -75,
      lifedrain: 0,
    },
    loot: [
      { name: 'Gold Coin', chance: 'very common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Great Mana Potion', chance: 'common' },
      { name: 'Ultimate Health Potion', chance: 'common' },
      { name: 'Silver Token', chance: 'uncommon' },
      { name: 'Gold Token', chance: 'uncommon' },
      { name: 'Shadow Sceptre', chance: 'rare' },
      { name: 'Book of Lies', chance: 'very rare' },
    ],
  },
  {
    name: 'Lokathmor',
    slug: 'Lokathmor',
    imageUrl: 'https://static.tibia.com/images/library/creatures/lokathmor.gif',
    boss: true,
    shortDescription:
      'Demoniczny boss z Secret Library, slaby na earth i energy, a odporny na fire, z klasycznym bibliotekowym lootem tokenowym.',
    accessQuest: 'Czesc The Secret Library Quest.',
    location: 'The Secret Library.',
    soloLevel: '500+',
    groupLevel: '300+',
    resistances: {
      physical: 0,
      earth: 25,
      fire: -75,
      ice: -30,
      energy: 25,
      holy: 0,
      death: 0,
      drown: 0,
      lifedrain: 0,
    },
    loot: [
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'Silver Token', chance: 'common' },
      { name: 'Gold Token', chance: 'uncommon' },
      { name: 'Knowledgeable Book', chance: 'uncommon' },
      { name: 'Ominous Book', chance: 'uncommon' },
      { name: 'Crystallized Anger', chance: 'rare' },
      { name: "Spellweaver's Robe", chance: 'rare' },
    ],
  },
  {
    name: 'Lord Azaram',
    slug: 'Lord-Azaram',
    imageUrl: 'https://static.tibia.com/images/library/creatures/lordazaram.gif',
    boss: true,
    shortDescription:
      "Jeden z bossow Grave Danger, oparty na fazie z Azaram's Soul i wymuszajacy dobre prowadzenie duszy przez fioletowy ogien.",
    accessQuest: 'Jeden z bossow Grave Danger Quest.',
    location: 'Ghostlands.',
    soloLevel: '900+',
    groupLevel: '450+',
    attackStyle: [
      'uderzenia wrecz',
      'earth beam',
      'male i duze poison wave',
      "faza z Azaram's Soul",
    ],
    resistances: {
      physical: 0,
      earth: -100,
      fire: 25,
      ice: 0,
      energy: -30,
      holy: 0,
      death: 0,
      drown: 0,
      lifedrain: 0,
    },
    loot: [
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Silver Token', chance: 'common' },
      { name: 'Ultimate Spirit Potion', chance: 'common' },
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Ancient Liche Bone', chance: 'uncommon' },
      { name: 'Rotten Heart', chance: 'uncommon' },
      { name: 'Final Judgement', chance: 'rare' },
      { name: 'Noble Cape', chance: 'rare' },
    ],
  },
  {
    name: 'Lord Retro',
    slug: 'Lord-Retro',
    imageUrl: 'https://static.tibia.com/images/library/creatures/lordretro.gif',
    boss: true,
    shortDescription:
      'Rocznicowy final 25 Years of Tibia Quest, bardziej mechaniczny niz lootowy, z praktycznie pelna niewrazliwoscia na standardowe obrazenia.',
    accessQuest: 'Finalny boss 25 Years of Tibia Quest.',
    location: 'Time Travel Dungeon.',
    soloLevel: '400+',
    groupLevel: '250+',
    resistances: {
      physical: -100,
      earth: -100,
      fire: -100,
      ice: -100,
      energy: -100,
      holy: -100,
      death: -100,
      drown: -100,
      lifedrain: -100,
    },
  },
  {
    name: 'Magma Bubble',
    slug: 'Magma-Bubble',
    imageUrl: 'https://static.tibia.com/images/library/creatures/magmacolossus.gif',
    boss: true,
    shortDescription:
      'Finalny boss Primal Ordeal stojacy w miejscu i zasypujacy arene projektylami fire oraz efektami obszarowymi.',
    accessQuest: 'Finalny boss Primal Ordeal Quest.',
    location: 'Sparkling Pools.',
    soloLevel: '1000+',
    groupLevel: '600+',
    attackStyle: [
      'stacjonarna walka',
      'fire balle',
      'obszarowe eksplozje',
      'duza presja dystansowa',
    ],
    resistances: {
      physical: 0,
      earth: -100,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
      drown: 0,
      lifedrain: 0,
    },
    loot: [
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'Ultimate Mana Potion', chance: 'common' },
      { name: 'Ultimate Health Potion', chance: 'common' },
      { name: 'Alicorn Headguard', chance: 'rare' },
      { name: 'Alicorn Quiver', chance: 'rare' },
      { name: 'Arboreal Crown', chance: 'rare' },
      { name: 'Spiritthorn Armor', chance: 'very rare' },
      { name: 'Spiritthorn Helmet', chance: 'very rare' },
    ],
  },
  {
    name: 'Maior Domus',
    slug: 'Maior-Domus',
    imageUrl: 'https://static.tibia.com/images/library/creatures/maiordomus.gif',
    boss: true,
    shortDescription:
      'Pierwsza forma Maior Domus z finalnej walki Make Believe Quest, dostepna tez w Boss Difficulty System.',
    accessQuest: 'Pojawia sie podczas Make Believe Quest i w Boss Difficulty System.',
    soloLevel: '1200+',
    groupLevel: '700+',
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
      drown: 0,
      lifedrain: 0,
    },
    loot: [
      { name: 'Figurine of Maior Domus', chance: 'rare' },
      { name: 'Moonsilver Strike Helm', chance: 'very rare' },
      { name: 'Moonsilver Trail Hood', chance: 'very rare' },
    ],
  },
];
