export const TIBIA_FANDOM_BATCH_1 = [
  {
    name: 'Tarbaz',
    slug: 'Tarbaz',
    imageUrl: 'https://static.tibia.com/images/library/creatures/tarbaz.gif',
    boss: true,
    shortDescription:
      'Demoniczny miniboss z Ferumbras’ Ascension nastawiony na obrażenia fire i death. Walka jest prosta mechanicznie, ale trzeba uważać na beam oraz niszczenie magic walli i wild growthów.',
    accessQuest: 'Wymaga dostępu do Ferumbras’ Ascension Quest i wejścia do Grounds of Despair.',
    location: 'Grounds of Despair, obszar questa Ferumbras’ Ascension Quest.',
    soloLevel: '500+',
    groupLevel: '300+',
    attackStyle: ['uderzenia wręcz', 'fala fire', 'beam fire', 'eksplozje death'],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'Silver Token', chance: 'very common' },
      { name: 'platinum coin', chance: 'common' },
      { name: 'great mana potion', chance: 'common' },
      { name: 'ultimate health potion', chance: 'common' },
      { name: 'demonic essence', chance: 'uncommon' },
      { name: 'Underworld Rod', chance: 'uncommon' },
      { name: 'Maimer', chance: 'rare' },
      { name: 'Shroud of Despair', chance: 'rare' },
    ],
  },
  {
    name: 'Abyssador',
    slug: 'Abyssador',
    imageUrl: 'https://static.tibia.com/images/library/creatures/abyssador.gif',
    boss: true,
    shortDescription:
      'Najtrudniejszy z bossów Warzone, bardzo mobilny i często staje się niewidzialny. Zadaje dużo obrażeń earth i fizycznych, a do tego potrafi bardzo mocno się leczyć.',
    accessQuest: 'Wymaga dostępu do Warzone 3.',
    location: 'Warzone 3.',
    soloLevel: '650+',
    groupLevel: '350+',
    attackStyle: [
      'mocne uderzenia wręcz',
      'fala earth',
      'bomby earth',
      'niewidzialność i silne leczenie',
    ],
    resistances: {
      physical: 0,
      earth: -100,
      fire: -75,
      ice: -75,
      energy: -75,
      holy: 0,
      death: -75,
    },
    loot: [
      { name: "Abyssador's Lash", chance: 'very common' },
      { name: 'Crystal Crossbow', chance: 'common' },
      { name: 'Crystalline Axe', chance: 'common' },
      { name: 'Crystalline Sword', chance: 'common' },
      { name: 'Decorative Ribbon', chance: 'uncommon' },
      { name: 'Mycological Bow', chance: 'uncommon' },
      { name: 'Mycological Mace', chance: 'uncommon' },
      { name: 'Shiny Blade', chance: 'rare' },
    ],
  },
  {
    name: 'Adventurer Group',
    slug: 'Adventurer-Group',
    imageUrl: 'https://static.tibia.com/images/library/creatures/adventurergroup.gif',
    boss: true,
    shortDescription:
      'To starcie z pięcioma przeciwnikami naraz, po jednym na każdą profesję, a po zejściu na czerwone HP przechodzą oni w silniejsze formy avatarów. Trzeba unikać bright crystalów z mana drainem i przygotować się, że po ich zabiciu pojawia się Fatal Bug.',
    accessQuest: 'Wymaga Jade Dragon Head i dostępu do The Roost of the Graveborn Quest.',
    location: 'Greenshore, arena questa The Roost of the Graveborn Quest.',
    soloLevel: '700+',
    groupLevel: '350+',
    attackStyle: [
      'mieszane obrażenia wszystkich żywiołów',
      'ataki dystansowe i wręcz',
      'formy avatarów z większą ochroną',
      'bright crystale z mana drainem',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'Worn Guide Book', chance: 'rare' },
      {
        name: 'Ancient Crypt Rune',
        chance: 'rare',
        notes: 'Może wypaść dopiero po pełnym ukończeniu questa.',
      },
    ],
  },
  {
    name: 'Ahau',
    slug: 'Ahau',
    imageUrl: 'https://static.tibia.com/images/library/creatures/ahau.gif',
    boss: true,
    shortDescription:
      'Przywódca Iksów walczący głównie obrażeniami earth i fire. Najważniejsza mechanika to cztery życia oraz coraz większa strefa lawy po każdym odrodzeniu.',
    accessQuest:
      'Wymaga dostępu do Iksupan w Adventures of Galthen Quest i użycia The Key Intihuatac.',
    location: 'Iksupan, północna część trzeciego poziomu miasta, arena z niebieskimi płomieniami.',
    soloLevel: '300+',
    groupLevel: '220+',
    attackStyle: [
      'uderzenia wręcz z poisonem',
      'strike earth',
      'beam fire',
      'pierścienie i bomby earth',
    ],
    resistances: {
      physical: 0,
      earth: -100,
      fire: 0,
      ice: 25,
      energy: 0,
      holy: 0,
      death: -100,
    },
    loot: [
      { name: 'gold coin', chance: 'very common' },
      { name: 'Great Health Potion', chance: 'common' },
      { name: 'Great Mana Potion', chance: 'common' },
      { name: 'Great Spirit Potion', chance: 'common' },
      { name: 'diamond', chance: 'common' },
      { name: 'bar of gold', chance: 'uncommon' },
      { name: 'Amber with a Bug', chance: 'uncommon' },
      { name: 'The Living Idol of Tukh', chance: 'rare' },
    ],
  },
  {
    name: 'Amenef The Burning',
    slug: 'Amenef-The-Burning',
    imageUrl: 'https://static.tibia.com/images/library/creatures/ameneftheburning.gif',
    boss: true,
    shortDescription:
      'Ognisty miniboss kultystów Fafnara z Kilmaresh. Sam zestaw ciosów nie jest skomplikowany, ale bije solidnie w zwarciu i premiuje graczy z ochroną na fire oraz energy.',
    accessQuest:
      'Miniboss linii Wanted w Kilmaresh Quest, dostępny przez teleport w Ruins of Nuur.',
    location: 'Ruins of Nuur, za teleportem wewnątrz ruin.',
    soloLevel: '250+',
    groupLevel: '180+',
    attackStyle: [
      'mocne uderzenia wręcz',
      'obrażenia fire',
      'obrażenia energy',
      'presja w zwarciu',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: -75,
      ice: 25,
      energy: -75,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'crystal coin', chance: 'common' },
      { name: 'Mastermind Potion', chance: 'common' },
      { name: 'Blue Gem', chance: 'uncommon' },
      { name: 'Golden Mask', chance: 'uncommon' },
      { name: 'Focus Cape', chance: 'uncommon' },
      { name: 'Eye-Embroidered Veil', chance: 'rare' },
      { name: 'Tagralt-Inlaid Scabbard', chance: 'rare' },
      { name: 'Sea Horse Figurine', chance: 'rare' },
    ],
  },
  {
    name: 'Anomaly',
    slug: 'Anomaly',
    imageUrl: 'https://static.tibia.com/images/library/creatures/anomaly.gif',
    boss: true,
    shortDescription:
      'Boss z Heart of Destruction, który regularnie przechodzi w formę Charged Anomaly odporną na zwykły damage. Wtedy trzeba przeciągać go przez czerwone vortexy, bo to one zdejmują mu życie.',
    accessQuest:
      'Wymaga rozpoczęcia Heart of Destruction Quest i ukończenia dostępu do walki w Otherworld.',
    location: 'Otherworld, arena bossa w ścieżce ankrahmuńskiej.',
    soloLevel: '450+',
    groupLevel: '250+',
    attackStyle: [
      'uderzenia wręcz',
      'transformacja w Charged Anomaly',
      'silniejsze ciosy w formie naładowanej',
      'częsty retarget',
    ],
    resistances: {
      physical: -75,
      earth: -75,
      fire: -75,
      ice: -75,
      energy: -75,
      holy: -75,
      death: -75,
    },
    loot: [
      { name: 'Gold Token', chance: 'very common' },
      { name: 'Mysterious Remains', chance: 'very common' },
      { name: 'gold coin', chance: 'common' },
      { name: 'Great Spirit Potion', chance: 'common' },
      { name: 'great mana potion', chance: 'common' },
      { name: 'Curious Matter', chance: 'uncommon' },
      { name: 'Void Boots', chance: 'rare' },
      { name: 'Frozen Lightning', chance: 'rare' },
    ],
  },
  {
    name: 'Arbaziloth',
    slug: 'Arbaziloth',
    imageUrl: 'https://static.tibia.com/images/library/creatures/arbaziloth4spheres.gif',
    boss: true,
    shortDescription:
      'Finałowy boss No Rest for the Wicked Quest z wyraźną mechaniką faz i zdejmowania niewrażliwości wędką. Trzeba uważać na ciągłe przywołania, efekt Powerless i momenty, w których boss staje się nietykalny aż do przeciągnięcia go przez fioletowy ogień.',
    accessQuest:
      'Finał No Rest for the Wicked Quest, dostęp do areny na -3 poziomie Azzilon Castle.',
    location: 'Azzilon Castle.',
    soloLevel: '900+',
    groupLevel: '500+',
    attackStyle: [
      'uderzenia wręcz',
      'nakładanie Powerless',
      'okresowa niewrażliwość',
      'przywołania i wzmacniana faza końcowa',
    ],
    resistances: {
      physical: -75,
      earth: 0,
      fire: -75,
      ice: -75,
      energy: 0,
      holy: 0,
      death: -75,
    },
    loot: [
      { name: 'Strong Mana Potion', chance: 'common' },
      { name: 'Ultimate Health Potion', chance: 'common' },
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Giant Ruby', chance: 'uncommon' },
      { name: 'Demonrage Sword', chance: 'rare' },
      { name: 'Demonfang Mask', chance: 'rare' },
      { name: 'Dreadfire Headpiece', chance: 'very rare' },
      { name: 'Hellstalker Visor', chance: 'very rare' },
    ],
  },
  {
    name: 'Black Vixen',
    slug: 'Black-Vixen',
    imageUrl: 'https://static.tibia.com/images/library/creatures/vixen.gif',
    boss: true,
    shortDescription:
      'Liderka werefoxów walcząca na dystans i lubiąca znikanie oraz przywołania. Sama walka nie jest bardzo ciężka, ale paraliż, death beam i summon werefoxa potrafią szybko dołożyć obrażeń.',
    accessQuest: 'Solo boss w Grimvale Quest, część The Curse Spreads.',
    location: 'Cormaya, za Earth Portalem w jaskini werebestii.',
    soloLevel: '160+',
    groupLevel: '120+',
    attackStyle: [
      'atak dystansowy',
      'beam death',
      'paraliżujący stalagmite',
      'niewidzialność i summon werefoxa',
    ],
    resistances: {
      physical: 0,
      earth: -75,
      fire: 25,
      ice: -75,
      energy: -75,
      holy: 0,
      death: -75,
    },
    loot: [
      { name: 'Fox Paw', chance: 'very common' },
      { name: 'Werefox Tail', chance: 'very common' },
      { name: 'platinum coin', chance: 'common' },
      { name: 'Assassin Star', chance: 'common' },
      { name: 'Great Spirit Potion', chance: 'common' },
      { name: 'Moonlight Crystals', chance: 'semi-rare' },
      { name: 'Werefox Trophy', chance: 'semi-rare' },
      { name: 'Foxtail', chance: 'very rare' },
    ],
  },
  {
    name: 'Blight Mariner',
    slug: 'Blight-Mariner',
    imageUrl: 'https://static.tibia.com/images/library/creatures/blightmariner.gif',
    boss: true,
    shortDescription:
      'Boss z Between the Lines Quest oparty bardziej na mechanice niż na samych statystykach. Nie wolno bić go, gdy żyją Drowned Deck Hands, bo wtedy leczy 5000 HP, a z czasem arena zalewa się dodatkowymi spittersami.',
    accessQuest: 'Wymaga dostępu do Between the Lines Quest i wejścia przez obraz w Venore.',
    location: 'Venore, ukryta arena dostępna po kliknięciu obrazu.',
    soloLevel: '350+',
    groupLevel: '250+',
    attackStyle: [
      'uderzenia wręcz',
      'leczenie po trafieniach gdy żyją addy',
      'cykliczne wycofywanie się na statek',
      'ciągłe przywołania Drowned Deck Handów',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'platinum coin', chance: 'common' },
      { name: 'Small Topaz', chance: 'common' },
      { name: 'moonstone', chance: 'common' },
      { name: 'Sword Ring', chance: 'uncommon' },
      { name: 'Terra Boots', chance: 'uncommon' },
      { name: 'Gold Ingot', chance: 'uncommon' },
      { name: 'Proficiency Catalyst', chance: 'rare' },
      { name: 'Crystalline Armor', chance: 'rare' },
    ],
  },
  {
    name: 'Bloodback',
    slug: 'Bloodback',
    imageUrl: 'https://static.tibia.com/images/library/creatures/bloodhoof.gif',
    boss: true,
    shortDescription:
      'Lider wereboarów walczący głównie fizycznie i przez przywołanie wsparcia. To prosty solo boss, ale w zwarciu potrafi mocno przycisnąć, więc dystans i fire wciąż działają najlepiej.',
    accessQuest: 'Solo boss w Grimvale Quest, część The Curse Spreads.',
    location: 'Edron, za Earth Portalem w jaskini werebestii.',
    soloLevel: '150+',
    groupLevel: '110+',
    attackStyle: ['uderzenia wręcz', 'fizyczny burst', 'wzmocnienie berserk', 'summon wereboara'],
    resistances: {
      physical: 0,
      earth: -75,
      fire: 25,
      ice: 0,
      energy: -75,
      holy: 0,
      death: -75,
    },
    loot: [
      { name: 'platinum coin', chance: 'very common' },
      { name: 'Wereboar Hooves', chance: 'very common' },
      { name: 'Wereboar Tusks', chance: 'very common' },
      { name: 'Great Health Potion', chance: 'common' },
      { name: 'Wereboar Loincloth', chance: 'common' },
      { name: 'Dreaded Cleaver', chance: 'uncommon' },
      { name: 'Wereboar Trophy', chance: 'semi-rare' },
      { name: 'Spiked Squelcher', chance: 'semi-rare' },
    ],
  },
  {
    name: 'Bone Overlord',
    slug: 'Bone-Overlord',
    imageUrl: 'https://static.tibia.com/images/library/creatures/boneoverlordbosstiary.gif',
    boss: true,
    shortDescription:
      'Finał The Roost of the Graveborn Quest z rozbudowaną walką fazową. Najpierw trzeba zniszczyć soulcage’e i ogarniać teleporty, agony, curse oraz mana drain, a dopiero potem dobić właściwą phylactery z lootem.',
    accessQuest:
      'Wymaga ukończenia czterech poprzednich bossów w The Roost of the Graveborn Quest.',
    location: 'Forgotten Crypt pod Draconią.',
    soloLevel: '1000+',
    groupLevel: '600+',
    attackStyle: [
      'teleportowanie graczy do izolatki',
      'agony z oczu i wraithfire',
      'mana drain w czasie',
      'klątwa z obszarową eksplozją fizyczną',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Bonelord Eye', chance: 'common' },
      { name: 'Unholy Bone', chance: 'common' },
      { name: 'Haunted Blade', chance: 'uncommon' },
      { name: 'Giant Ruby', chance: 'uncommon' },
      { name: 'Giant Sapphire', chance: 'uncommon' },
      { name: 'Soul Trap', chance: 'rare' },
      {
        name: 'Necromantic Crypt Rune',
        chance: 'rare',
        notes: 'Drop pochodzi z Bonelords’s Phylactery, a nie bezpośrednio z modelu bossa.',
      },
    ],
  },
  {
    name: 'Brain Head',
    slug: 'Brain-Head',
    imageUrl: 'https://static.tibia.com/images/library/creatures/brainhead.gif',
    boss: true,
    shortDescription:
      'Undead boss z Feaster of Souls, którego trzeba bić głównie ice. Należy najpierw oczyścić część Cerebellumów i bardzo uważać na energię, bo ta leczy bossa, a fire według strategii też jest złym wyborem.',
    accessQuest: 'Wymaga postępu w Feaster of Souls Quest po misji Drain the Brain.',
    location: 'Netherworld.',
    soloLevel: '500+',
    groupLevel: '300+',
    attackStyle: [
      'uderzenia wręcz',
      'silne kontry po podejściu addów',
      'leczenie od obrażeń energy',
      'presja od Cerebellumów i Bad Thoughtów',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: -75,
      ice: 25,
      energy: -100,
      holy: 0,
      death: -75,
    },
    loot: [
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Ultimate Spirit Potion', chance: 'common' },
      { name: 'Ultimate Mana Potion', chance: 'common' },
      { name: 'Death Toll', chance: 'uncommon' },
      { name: "Brain Head's Giant Neuron", chance: 'rare' },
      { name: "Brain Head's Left Hemisphere", chance: 'rare' },
      { name: "Brain Head's Right Hemisphere", chance: 'rare' },
    ],
  },
  {
    name: 'Brokul',
    slug: 'Brokul',
    imageUrl: 'https://static.tibia.com/images/library/creatures/brokul.gif',
    boss: true,
    shortDescription:
      'Boss deathlingów z Secret Library, bardzo groźny dla graczy stojących na linii jego beamów. Nie wolno stać przed nim ani zbyt blisko, bo łączy mocne beamy z bombami, paraliżem i leczeniem.',
    accessQuest: 'Część The Secret Library Quest.',
    location: 'Deepling Ancestorial Grounds.',
    soloLevel: '450+',
    groupLevel: '250+',
    attackStyle: [
      'mocne beamy fire, holy i death',
      'bomby obszarowe',
      'paraliż dystansowy',
      'leczenie',
    ],
    resistances: {
      physical: 0,
      earth: -100,
      fire: -100,
      ice: -100,
      energy: 25,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'The True Book of Death', chance: 'very common' },
      { name: 'platinum coin', chance: 'common' },
      { name: 'Broccoli', chance: 'common' },
      { name: 'Red Gem', chance: 'common' },
      { name: 'Gold Ingot', chance: 'uncommon' },
      { name: 'Deepling Ceremonial Dagger', chance: 'rare' },
      { name: 'Deepling Fork', chance: 'rare' },
      { name: 'Small Diamond', chance: 'uncommon' },
    ],
  },
  {
    name: 'Chagorz',
    slug: 'Chagorz',
    imageUrl: 'https://static.tibia.com/images/library/creatures/chagorz.gif',
    boss: true,
    shortDescription:
      'Jeden z najcięższych bossów Rotten Blood Quest, mocno oparty na polach darkfield, pillarach i rotten charge. Jeśli drużyna źle zarządza ruchem albo dopuści do złych eksplozji i beamów, boss szybko zaczyna leczyć się i karać ogromnym burstem fire.',
    accessQuest:
      'Wymaga dostępu do Rotten Blood Quest i pełnego naładowania Rotten Charges w Gloom Pillars.',
    location: 'Gloom Pillars.',
    soloLevel: '1100+',
    groupLevel: '650+',
    attackStyle: [
      'pierścień energy o ogromnym zasięgu',
      'bomby i beam death',
      'pola darkfield leczące bossa',
      'summon Pillar of Dark Energy',
    ],
    resistances: {
      physical: 0,
      earth: -75,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Ultimate Mana Potion', chance: 'common' },
      { name: 'Ultimate Spirit Potion', chance: 'common' },
      { name: 'The Essence of Chagorz', chance: 'uncommon' },
      { name: 'Spiritual Horseshoe', chance: 'rare' },
      { name: 'Darklight Geode', chance: 'rare' },
      { name: 'Bag You Covet', chance: 'very rare' },
    ],
  },
  {
    name: 'Count Vlarkorth',
    slug: 'Count-Vlarkorth',
    imageUrl: 'https://static.tibia.com/images/library/creatures/countvlarkort.gif',
    boss: true,
    shortDescription:
      'Boss z Grave Danger Quest, który robi się uciążliwy głównie przez summonowanie minionów i fazy niewrażliwości. Trzeba trzymać Soulless Miniony z dala od niego i poprawnie używać szczątków dark vocationów, inaczej walka mocno się przeciąga.',
    accessQuest: 'Jeden z bossów Grave Danger Quest pod cmentarzem na północ od Edron.',
    location: 'Pod cmentarzem na północ od Edron.',
    soloLevel: '650+',
    groupLevel: '350+',
    attackStyle: [
      'uderzenia wręcz',
      'mocny beam fire',
      'summon Soulless Minionów',
      'leczenie i life steal',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: -75,
      ice: 0,
      energy: -75,
      holy: 0,
      death: 25,
    },
    loot: [
      { name: 'platinum coin', chance: 'very common' },
      { name: 'Silver Token', chance: 'very common' },
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Ultimate Mana Potion', chance: 'common' },
      { name: 'Ultimate Spirit Potion', chance: 'common' },
      { name: 'Medal of Valiance', chance: 'uncommon' },
      { name: 'Ancient Liche Bone', chance: 'rare' },
      { name: 'Final Judgement', chance: 'very rare' },
    ],
  },
  {
    name: 'Court Warlock',
    slug: 'Court-Warlock',
    imageUrl: 'https://static.tibia.com/images/library/creatures/courtwarlock.gif',
    boss: true,
    shortDescription:
      'Finał The Order of the Stag Quest zaczyna się od długiej gauntletowej obrony przeciw falom Raubritterów i zabójczemu death terenowi. Sam Court Warlock pojawia się dopiero po wyczyszczeniu minionów i jego końcowa siła zależy od tego, jak dobrze drużyna poradziła sobie wcześniej.',
    accessQuest:
      'Finalny boss The Order of the Stag Quest, po rozmowie z Captain Marie-Denise Banner na Isle of Ada.',
    location: 'Isle of Ada.',
    soloLevel: '600+',
    groupLevel: '400+',
    attackStyle: [
      'walka wręcz',
      'teleportowanie graczy po arenie',
      'ciągłe fale Raubritterów',
      'death tiles i finałowa faza bossa',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'platinum coin', chance: 'common' },
      { name: 'Ultimate Health Potion', chance: 'common' },
      { name: 'Ultimate Mana Potion', chance: 'common' },
      { name: 'Spellbook of Mind Control', chance: 'common' },
      { name: 'Twisted Marionette', chance: 'rare' },
      { name: 'Stag Plate', chance: 'very rare' },
      { name: 'Stag Spellbook', chance: 'very rare' },
    ],
  },
];
