export const TIBIA_FANDOM_BATCH_7 = [
  {
    name: 'The Time Guardian',
    slug: 'The-Time-Guardian',
    imageUrl: 'https://static.tibia.com/images/library/creatures/timeguardian.gif',
    boss: true,
    shortDescription:
      'Maszynowy miniboss z Forgotten Knowledge Quest, walczacy w kilku formach ze wspolnym paskiem zycia. W podstawowej postaci najlepiej przyjmuje obrazenia fizyczne, a zywiolami bije wyraznie slabiej.',
    accessQuest:
      'Wymagany dostep do Forgotten Knowledge Quest oraz wejscie przez Holy Portal za Astral Shaper Dungeon.',
    location: 'Gleboko pod polnocno-zachodnim Edron, arena The Time Guardian.',
    soloLevel: '500+',
    groupLevel: '300+',
    attackStyle: [
      'mocne uderzenia wrecz',
      'fire strike',
      'energy wave',
      'zmiana form ze wspolnym hp',
    ],
    resistances: {
      physical: 0,
      earth: -75,
      fire: -75,
      ice: 0,
      energy: -75,
      holy: 0,
      death: -75,
    },
    loot: [
      { name: 'gold coin', chance: 'very common' },
      { name: 'platinum coin', chance: 'common' },
      { name: 'ultimate health potion', chance: 'common' },
      { name: 'silver token', chance: 'uncommon' },
      { name: 'guardian boots', chance: 'rare' },
      { name: 'frozen time', chance: 'rare' },
    ],
  },
  {
    name: 'The Unarmored Voidborn',
    slug: 'The-Unarmored-Voidborn',
    imageUrl: 'https://static.tibia.com/images/library/creatures/voidbornvulnerable.gif',
    boss: true,
    shortDescription:
      'Druga forma voidborna z Cults of Tibia Quest, skrajnie podatna na praktycznie kazdy typ obrazen. Mimo olbrzymiej slabej odpornosci ma duzo hp, wiec walka nadal trwa chwile.',
    accessQuest: 'Pojawia sie po zabiciu The Armored Voidborn w Cults of Tibia Quest.',
    location: 'Kryjowka orkowego kultu w Edron Orc Cave.',
    soloLevel: '220+',
    groupLevel: '140+',
    attackStyle: [
      'mocne uderzenia wrecz',
      'death wave',
      'energy chain attack',
      'walka bez zlozonej mechaniki',
    ],
    resistances: {
      physical: 50,
      earth: 50,
      fire: 50,
      ice: 50,
      energy: 50,
      holy: 50,
      death: 50,
    },
    loot: [
      { name: 'gold coin', chance: 'very common' },
      { name: 'platinum coin', chance: 'common' },
      { name: 'great mana potion', chance: 'common' },
      { name: 'silver token', chance: 'uncommon' },
      { name: 'gold token', chance: 'uncommon' },
      { name: 'heart of the mountain', chance: 'rare' },
    ],
  },
  {
    name: 'The Unwelcome',
    slug: 'The-Unwelcome',
    imageUrl: 'https://static.tibia.com/images/library/creatures/theunwelcome.gif',
    boss: true,
    shortDescription:
      'Archfoe z Feaster of Souls Quest o bardzo wysokich odpornosciach na wszystkie podstawowe zrodla obrazen. To prostsza mechanicznie walka, ale wymaga solidnego sustainu i cierpliwego bicia.',
    accessQuest: 'Czesc Feaster of Souls Quest.',
    location: 'Zarganash.',
    soloLevel: '450+',
    groupLevel: '250+',
    attackStyle: ['uderzenia wrecz', 'duza wytrzymalosc', 'presja przez dlugi czas walki'],
    resistances: {
      physical: -75,
      earth: -75,
      fire: -75,
      ice: -75,
      energy: -75,
      holy: -75,
      death: -75,
    },
    loot: [
      { name: 'crystal coin', chance: 'common' },
      { name: 'berserk potion', chance: 'common' },
      { name: 'ultimate mana potion', chance: 'common' },
      { name: 'writhing heart', chance: 'uncommon' },
      { name: 'soulforged lantern', chance: 'rare' },
      { name: 'fabulous legs', chance: 'very rare' },
    ],
  },
  {
    name: 'The Winter Bloom',
    slug: 'The-Winter-Bloom',
    imageUrl: 'https://static.tibia.com/images/library/creatures/winterbloom.gif',
    boss: true,
    shortDescription:
      'Asura boss laczacy ice i death z niewidzialnoscia, paraliem oraz mana drainem. Najlatwiej wejsc przygotowanym na lod i szybko skrocic walke, bo potrafi tez sie podleczac.',
    accessQuest:
      'Dostep z Asura Palace Quest, co 20 godzin po pokonaniu Solitary Frost Dragon i 2 Greater Energy Elementali.',
    location: 'Asura Palace.',
    soloLevel: '250+',
    groupLevel: '150+',
    attackStyle: [
      'uderzenia wrecz',
      'ice missile i ice bomb',
      'death bomb',
      'paralyze, niewidzialnosc i mana drain',
    ],
    resistances: {
      physical: 0,
      earth: -30,
      fire: 25,
      ice: -100,
      energy: 0,
      holy: 0,
      death: -30,
    },
    loot: [
      { name: 'gold coin', chance: 'very common' },
      { name: 'great mana potion', chance: 'common' },
      { name: 'ultimate health potion', chance: 'common' },
      { name: 'demonic essence', chance: 'common' },
      { name: 'glacier robe', chance: 'rare' },
      { name: 'golden lotus brooch', chance: 'rare' },
    ],
  },
  {
    name: 'Timira The Many-Headed',
    slug: 'Timira-The-Many-Headed',
    imageUrl: 'https://static.tibia.com/images/library/creatures/timira.gif',
    boss: true,
    shortDescription:
      'Finalna naga z Within the Tides Quest, walczaca glownie z bliska, ale rozlewajaca obrazenia po calej sali lancuchami i polami ognia. Wiekszosc zywiolow dziala na nia dobrze, a sorcererzy zwykle lepiej wypadaja na single target.',
    accessQuest: 'Czesc Within the Tides Quest.',
    location: 'Emerald Gardens na wyspie Marapur.',
    soloLevel: '700+',
    groupLevel: '400+',
    attackStyle: [
      'uderzenia wrecz',
      'fire bomby i ringi',
      'death chain',
      'energy strike i mana drain chain',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: -30,
      ice: 25,
      energy: -30,
      holy: 0,
      death: -30,
    },
    loot: [
      { name: 'crystal coin', chance: 'common' },
      { name: 'ultimate mana potion', chance: 'common' },
      { name: 'naga basin', chance: 'uncommon' },
      { name: "piece of Timira's sensors", chance: 'rare' },
      { name: "one of Timira's many heads", chance: 'rare' },
      { name: 'naga quiver', chance: 'very rare' },
    ],
  },
  {
    name: 'Tropical Desolator',
    slug: 'Tropical-Desolator',
    imageUrl: 'https://static.tibia.com/images/library/creatures/tropicaldesolator.gif',
    boss: true,
    shortDescription:
      'Iksowy boss z Between the Lines Quest, wspierany przez egzotyczne owoce z losowymi efektami. Najwieksze ryzyko daje heal dla bossa i fear, wiec trzeba stale kontrolowac pozycje.',
    accessQuest: 'Czesc Between the Lines Quest.',
    location: 'Liberty Bay.',
    soloLevel: '250+',
    groupLevel: '180+',
    attackStyle: [
      'uderzenia wrecz',
      'przywolania',
      'wybuchajace owoce z earth damage',
      'fear i leczenie bossa',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 25,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'platinum coin', chance: 'very common' },
      { name: 'white pearl', chance: 'common' },
      { name: 'black pearl', chance: 'common' },
      { name: 'gold ingot', chance: 'uncommon' },
      { name: 'proficiency catalyst', chance: 'rare' },
      { name: 'scallop shell', chance: 'very rare' },
    ],
  },
  {
    name: 'Unaz The Mean',
    slug: 'Unaz-The-Mean',
    imageUrl: 'https://static.tibia.com/images/library/creatures/unaz.gif',
    boss: true,
    shortDescription:
      'Upiorny boss z Feaster of Souls Quest, odporny na physical i energy, a calkowicie niewrazliwy na death. Walczy kontaktowo, ale potrafi dorzucic mocne komba zywiolowe, wiec warto podejsc z dobra ochrona.',
    accessQuest: 'Czesc Feaster of Souls Quest.',
    location: 'Netherworld.',
    soloLevel: '400+',
    groupLevel: '250+',
    attackStyle: ['uderzenia wrecz', 'mocne komba energy i physical', 'life drain', 'death damage'],
    resistances: {
      physical: -30,
      earth: 0,
      fire: 0,
      ice: 25,
      energy: -30,
      holy: 0,
      death: -100,
    },
    loot: [
      { name: 'platinum coin', chance: 'common' },
      { name: 'ivory comb', chance: 'common' },
      { name: 'moonstone', chance: 'common' },
      { name: 'skull coin', chance: 'uncommon' },
      { name: 'death toll', chance: 'rare' },
      { name: 'pair of nightmare boots', chance: 'rare' },
    ],
  },
  {
    name: 'Urmahlullu The Weakened',
    slug: 'Urmahlullu-The-Weakened',
    imageUrl: 'https://static.tibia.com/images/library/creatures/urmahlulluweakest.gif',
    boss: true,
    shortDescription:
      'Oslabiona forma urmahlullu z Kilmaresh, ktora mimo nazwy nadal ma duzo zycia i nagradza mocnym burstem fire. To raczej statyczny boss do ustawienia i szybkiego fokusowania.',
    accessQuest: 'Czesc Kilmaresh Quest.',
    location: 'Issavi, Green Belt.',
    soloLevel: '400+',
    groupLevel: '250+',
    attackStyle: ['uderzenia wrecz', 'walka w zwarciu', 'prosta mechanika bez wielu faz'],
    resistances: {
      physical: 0,
      earth: 0,
      fire: -100,
      ice: 0,
      energy: -30,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'platinum coin', chance: 'common' },
      { name: 'supreme health potion', chance: 'common' },
      { name: 'ultimate mana potion', chance: 'common' },
      { name: 'silver token', chance: 'uncommon' },
      { name: 'winged boots', chance: 'rare' },
      { name: 'sunray emblem', chance: 'very rare' },
    ],
  },
  {
    name: 'Utua Stone Sting',
    slug: 'Utua-Stone-Sting',
    imageUrl: 'https://static.tibia.com/images/library/creatures/utua.gif',
    boss: true,
    shortDescription:
      'Pajeczy boss z watku An Ancient Feud, oparty na poisonie i physicalu. Jest wolny, wiec dystans ma sporo kontroli nad walka, a knight moze ograniczyc zagrozenie ustawieniem po skosie.',
    accessQuest: 'Czesc Grimvale Quest, etap An Ancient Feud.',
    location: 'Lion Sanctum.',
    soloLevel: '180+',
    groupLevel: '120+',
    attackStyle: ['uderzenia wrecz', 'blood wave', 'poison hit', 'poison ball'],
    resistances: {
      physical: 0,
      earth: -30,
      fire: -30,
      ice: 0,
      energy: -30,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'platinum coin', chance: 'common' },
      { name: 'ultimate health potion', chance: 'common' },
      { name: "Utua's Poison", chance: 'uncommon' },
      { name: 'gold ingot', chance: 'uncommon' },
      { name: 'magic plate armor', chance: 'rare' },
      { name: 'skull helmet', chance: 'rare' },
    ],
  },
  {
    name: 'Vemiath',
    slug: 'Vemiath',
    imageUrl: 'https://static.tibia.com/images/library/creatures/vemiath.gif',
    boss: true,
    shortDescription:
      'Rotten Blood boss z bardzo ciezka mechanika agony, pol darklight i eksplodujacego Rotten Charge. Sama odpornosc jest neutralna, ale walka wymaga perfekcyjnego ruchu i podzialu rol.',
    accessQuest: 'Jeden z bossow Rotten Blood Quest.',
    location: 'Darklight Core.',
    soloLevel: '1200+',
    groupLevel: '600+',
    attackStyle: [
      'mocne uderzenia wrecz',
      'death beam',
      'great energy ring',
      'mana drain, agony i przywolania',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'crystal coin', chance: 'common' },
      { name: 'ultimate mana potion', chance: 'common' },
      { name: 'supreme health potion', chance: 'common' },
      { name: 'raw watermelon tourmaline', chance: 'uncommon' },
      { name: "Vemiath's Infused Basalt", chance: 'rare' },
      { name: 'bag you covet', chance: 'very rare' },
    ],
  },
  {
    name: 'Vladrukh',
    slug: 'Vladrukh',
    imageUrl: 'https://static.tibia.com/images/library/creatures/vladrukh.gif',
    boss: true,
    shortDescription:
      'Boss z Bloody Tusks Quest, o ktorym wiki podaje niewiele szczegolow bojowych. Traktuj go jako pozniejszy questowy cel z nastawieniem na wytrzymanie i loot endgame.',
    accessQuest: 'Czesc Bloody Tusks Quest.',
    soloLevel: '500+',
    groupLevel: '300+',
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'platinum coin', chance: 'common' },
      { name: 'ultimate mana potion', chance: 'common' },
      { name: 'greater proficiency catalyst', chance: 'uncommon' },
      { name: 'blood preservation', chance: 'rare' },
      { name: 'blood sceptre', chance: 'rare' },
      { name: 'skull belt', chance: 'rare' },
    ],
  },
  {
    name: 'Vok The Freakish',
    slug: 'Vok-The-Freakish',
    imageUrl: 'https://static.tibia.com/images/library/creatures/vok.gif',
    boss: true,
    shortDescription:
      'Duchowy boss z Feaster of Souls Quest, bardzo twardy na death i energy, ale slabszy na ice. Sama strona nie opisuje wielu mechanik, dlatego walka zwykle sprowadza sie do ostroznego focusu i trzymania ochron.',
    accessQuest: 'Czesc Feaster of Souls Quest.',
    location: 'Netherworld.',
    soloLevel: '450+',
    groupLevel: '250+',
    attackStyle: ['uderzenia wrecz', 'presja w zwarciu', 'wysoka odpornosc na death i energy'],
    resistances: {
      physical: -30,
      earth: 0,
      fire: 0,
      ice: 25,
      energy: -100,
      holy: 0,
      death: -100,
    },
    loot: [
      { name: 'platinum coin', chance: 'common' },
      { name: 'cursed bone', chance: 'common' },
      { name: 'skull coin', chance: 'uncommon' },
      { name: 'death toll', chance: 'rare' },
      { name: 'ornate crossbow', chance: 'rare' },
      { name: 'pair of nightmare boots', chance: 'rare' },
    ],
  },
  {
    name: 'Wrathful Archivist',
    slug: 'Wrathful-Archivist',
    imageUrl: 'https://static.tibia.com/images/library/creatures/wrathfularchivist.gif',
    boss: true,
    shortDescription:
      'Biblioteczny boss z Between the Lines Quest, odpornosci ma neutralne, ale cala trudnosc bierze sie z mechanik aktywowanych przez niebieskie ksiazki. Bez szybkiego ogarniania run, duchow i zwierzat pozostaje niesmiertelny.',
    accessQuest: 'Jeden z bossow Between the Lines Quest.',
    location: 'Yalahar, na dachu domu Soilance po uzyciu levitate.',
    soloLevel: '250+',
    groupLevel: '180+',
    attackStyle: [
      'death damage',
      'energy damage',
      'mana drain',
      'okna podatnosci od mechanik z ksiazkami',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'platinum coin', chance: 'common' },
      { name: 'strong mana potion', chance: 'common' },
      { name: 'great mana potion', chance: 'common' },
      { name: 'blank imbuement scroll', chance: 'uncommon' },
      { name: 'proficiency catalyst', chance: 'rare' },
      { name: 'sand-filled horn', chance: 'very rare' },
    ],
  },
  {
    name: 'Yirkas Blue Scales',
    slug: 'Yirkas-Blue-Scales',
    imageUrl: 'https://static.tibia.com/images/library/creatures/yirkass.gif',
    boss: true,
    shortDescription:
      'Jaszczurzy boss z An Ancient Feud, bazujacy glownie na energy i earth. Dystans ma tu przewage, bo mozna ograniczac jego fale i wykorzystywac filary do bezpieczniejszego kitingu.',
    accessQuest: 'Czesc Grimvale Quest, etap An Ancient Feud.',
    location: 'Lion Sanctum.',
    soloLevel: '180+',
    groupLevel: '120+',
    attackStyle: ['uderzenia wrecz', 'energy strike i energy ball', 'energy bomb', 'earth wave'],
    resistances: {
      physical: 0,
      earth: -30,
      fire: -30,
      ice: 0,
      energy: -30,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'platinum coin', chance: 'common' },
      { name: 'ultimate health potion', chance: 'common' },
      { name: "Yirkas' Egg", chance: 'uncommon' },
      { name: 'gold ingot', chance: 'uncommon' },
      { name: 'alloy legs', chance: 'rare' },
      { name: 'ornate crossbow', chance: 'rare' },
    ],
  },
  {
    name: 'Zamulosh',
    slug: 'Zamulosh',
    imageUrl: 'https://static.tibia.com/images/library/creatures/zamulosh.gif',
    boss: true,
    shortDescription:
      "Demoniczny slug Ferumbras' Ascension, walczacy z klonami, niewidzialnoscia i teleportami do centrum sali. Najwygodniej ubijac go obszarowo, bo skupienie tylko prawdziwej kopii zwykle spowalnia walke.",
    accessQuest: "Czesc Ferumbras' Ascension Quest jako slug Bazira.",
    location: 'Grounds of Deceit.',
    soloLevel: '500+',
    groupLevel: '300+',
    attackStyle: [
      'uderzenia wrecz',
      'death wave',
      'life drain i poison',
      'niewidzialnosc oraz przywolania klonow',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: -30,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'platinum coin', chance: 'common' },
      { name: 'great mana potion', chance: 'common' },
      { name: 'silver token', chance: 'uncommon' },
      { name: 'demonic essence', chance: 'common' },
      { name: 'book of lies', chance: 'rare' },
      { name: 'rift crossbow', chance: 'rare' },
    ],
  },
];
