export const TIBIA_FANDOM_BATCH_5 = [
  {
    name: 'Scarlett Etzel',
    slug: 'Scarlett-Etzel',
    imageUrl: 'https://static.tibia.com/images/library/creatures/scarlettetzelstill.gif',
    boss: true,
    shortDescription:
      "Boss z Cobra Bastion z mechanika luster i Galthen's Chestplate. Najwieksze ryzyko daje leczenie przy zlym oknie podatnosci oraz potezny wybuch earth podczas poprawnego trafienia.",
    accessQuest:
      'Wymagany dostep do Cobra Bastion i mozliwosc wejscia do sali Scarlet w ramach tego obszaru.',
    location: 'Cobra Bastion.',
    soloLevel: '500+',
    groupLevel: '300+',
    attackStyle: [
      'uderzenia wrecz',
      'holy beam',
      'death strike',
      'wybuch earth przy mechanice luster',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'platinum coin', chance: 'very common' },
      { name: 'supreme health potion', chance: 'common' },
      { name: 'ultimate mana potion', chance: 'common' },
      { name: 'silver token', chance: 'common' },
      { name: 'cobra axe', chance: 'rare' },
      { name: 'cobra crossbow', chance: 'rare' },
      { name: 'the cobra amulet', chance: 'very rare' },
    ],
  },
  {
    name: 'Shadowpelt',
    slug: 'Shadowpelt',
    imageUrl: 'https://static.tibia.com/images/library/creatures/blackpelt.gif',
    boss: true,
    shortDescription:
      'Lider werebearow z Grimvale, walczacy glownie w zwarciu i wspierajacy sie leczeniem oraz summonem. Sama walka jest prosta, ale przedluzanie jej daje bossowi czas na odnowienie zycia.',
    accessQuest: 'Czesc Grimvale Quest, etap The Curse Spreads.',
    location: 'Cormaya, po przejsciu przez Earth Portal w jaskini werebestii.',
    soloLevel: '120+',
    groupLevel: '80+',
    attackStyle: ['uderzenia wrecz', 'samoleczenie', 'przywolanie werebeara'],
    resistances: {
      physical: 0,
      earth: -30,
      fire: 25,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'gold coin', chance: 'very common' },
      { name: 'platinum coin', chance: 'common' },
      { name: 'werebear fur', chance: 'common' },
      { name: 'werebear skull', chance: 'common' },
      { name: 'ultimate health potion', chance: 'uncommon' },
      { name: 'moonlight crystals', chance: 'semi-rare' },
      { name: 'silver token', chance: 'semi-rare' },
      { name: 'werebear trophy', chance: 'rare' },
    ],
  },
  {
    name: 'Sharpclaw',
    slug: 'Sharpclaw',
    imageUrl: 'https://static.tibia.com/images/library/creatures/sharpclaw.gif',
    boss: true,
    shortDescription:
      'Przywodca werebadgerow z Grimvale, nastawiony na zwarcie i irytujace wsparcie kontrola many. Dodatkowe zagrozenie tworza invis, oslabienie magii i przywolany werebadger.',
    accessQuest: 'Czesc Grimvale Quest, etap The Curse Spreads.',
    location: 'Edron, po teleporcie w jaskini werebestii.',
    soloLevel: '110+',
    groupLevel: '70+',
    attackStyle: ['uderzenia wrecz', 'mana drain', 'niewidzialnosc', 'przywolanie werebadgera'],
    resistances: {
      physical: 0,
      earth: -30,
      fire: 25,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'gold coin', chance: 'very common' },
      { name: 'platinum coin', chance: 'common' },
      { name: 'werebadger claws', chance: 'common' },
      { name: 'werebadger skull', chance: 'common' },
      { name: 'great mana potion', chance: 'common' },
      { name: 'moonlight crystals', chance: 'uncommon' },
      { name: 'silver token', chance: 'uncommon' },
      { name: 'wolf backpack', chance: 'very rare' },
    ],
  },
  {
    name: 'Shulgrax',
    slug: 'Shulgrax',
    imageUrl: 'https://static.tibia.com/images/library/creatures/shulgrax.gif',
    boss: true,
    shortDescription:
      "Ciezki demoniczny boss z Ferumbras' Ascension, ktory laczy wysokie melee z fire i smiercionosnym sustainem. Bloker traci na nim sporo skutecznosci przez czeste obnizanie skilli melee.",
    accessQuest: "Wymagany dostep do Ferumbras' Ascension Quest i Dark Torturer Seal.",
    location: "Grounds of Damnation, obszar questa Ferumbras' Ascension.",
    soloLevel: '600+',
    groupLevel: '350+',
    attackStyle: ['mocne uderzenia wrecz', 'fire wave', 'fire beam', 'leczenie'],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 25,
      ice: 0,
      energy: 25,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'silver token', chance: 'very common' },
      { name: 'gold coin', chance: 'common' },
      { name: 'platinum coin', chance: 'common' },
      { name: 'great mana potion', chance: 'common' },
      { name: 'great spirit potion', chance: 'common' },
      { name: 'underworld rod', chance: 'uncommon' },
      { name: 'pair of iron fists', chance: 'rare' },
      { name: 'treader of torment', chance: 'very rare' },
    ],
  },
  {
    name: 'Sir Baeloc',
    slug: 'Sir-Baeloc',
    imageUrl: 'https://static.tibia.com/images/library/creatures/sirbaeloc.gif',
    boss: true,
    shortDescription:
      'Undead boss z Grave Danger, ktory sam w sobie nie jest najgorszy, ale wymusza rownoczesne ubicie z Sir Nictrosem. Dodatkowy problem tworza summony i leczenie od death damage.',
    accessQuest: 'Wymagany postep w Grave Danger Quest i wejscie na cmentarz Darashii.',
    location: 'Cmentarz w Darashii.',
    soloLevel: '900+',
    groupLevel: '450+',
    attackStyle: [
      'hex',
      'przywolania',
      'presja w zwarciu',
      'mechanika wspolnego killu z Sir Nictrosem',
    ],
    resistances: {
      physical: 0,
      earth: -30,
      fire: 25,
      ice: -30,
      energy: 0,
      holy: 25,
      death: -100,
    },
    loot: [
      { name: 'silver token', chance: 'very common' },
      { name: 'platinum coin', chance: 'common' },
      { name: 'ultimate spirit potion', chance: 'common' },
      { name: 'supreme health potion', chance: 'common' },
      { name: 'ultimate mana potion', chance: 'common' },
      { name: 'ancient liche bone', chance: 'uncommon' },
      { name: 'rotten heart', chance: 'rare' },
      { name: 'final judgement', chance: 'rare' },
    ],
  },
  {
    name: 'Sir Nictros',
    slug: 'Sir-Nictros',
    imageUrl: 'https://static.tibia.com/images/library/creatures/sirnictros.gif',
    boss: true,
    shortDescription:
      'Brat Sir Baeloca i druga polowa pary z Grave Danger. Kluczowe jest ubijanie obu bossow naraz, bo inaczej beda sie wzajemnie leczyc, a death damage dodatkowo bardzo mu pomaga.',
    accessQuest: 'Wymagany postep w Grave Danger Quest i wejscie na cmentarz Darashii.',
    location: 'Cmentarz w Darashii.',
    soloLevel: '900+',
    groupLevel: '450+',
    attackStyle: [
      'hex',
      'przywolania',
      'presja w zwarciu',
      'mechanika wspolnego killu z Sir Baelokiem',
    ],
    resistances: {
      physical: 0,
      earth: -75,
      fire: 25,
      ice: -30,
      energy: 0,
      holy: 25,
      death: -100,
    },
    loot: [{ name: 'death oyoroi', chance: 'rare' }],
  },
  {
    name: 'Sister Hetai',
    slug: 'Sister-Hetai',
    imageUrl: 'https://static.tibia.com/images/library/creatures/sisterhetai.gif',
    boss: true,
    shortDescription:
      'Miniboss kultystow Fafnara z Kilmaresh, oparty glownie na mocnym melee i presji w zwarciu. Nie ma rozbudowanej mechaniki, ale jej wytrzymalosc i szybki kontakt karza slabo przygotowane postacie.',
    accessQuest:
      'Miniboss misji Wanted w Kilmaresh Quest, dostepny przez teleport w Kilmaresh Catacombs.',
    location: 'Kilmaresh Catacombs, za teleportem w katakumbach.',
    soloLevel: '250+',
    groupLevel: '180+',
    attackStyle: ['uderzenia wrecz', 'presja w zwarciu'],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 50,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'crystal coin', chance: 'common' },
      { name: 'gold ingot', chance: 'uncommon' },
      { name: 'lightning legs', chance: 'uncommon' },
      { name: 'focus cape', chance: 'uncommon' },
      { name: 'terra hood', chance: 'uncommon' },
      { name: 'eye-embroidered veil', chance: 'rare' },
      { name: 'sea horse figurine', chance: 'rare' },
      { name: 'Tagralt-Inlaid Scabbard', chance: 'rare' },
    ],
  },
  {
    name: 'Soul Of Dragonking Zyrtarch',
    slug: 'Soul-Of-Dragonking-Zyrtarch',
    imageUrl: 'https://static.tibia.com/images/library/creatures/dragonkingzyrtrachkillable.gif',
    boss: true,
    shortDescription:
      'Smiertelna forma Dragonking Zyrtarcha z Forgotten Knowledge. Wiki ma skromny opis walki, ale boss wyraznie nalezy do drakenow i jest calkowicie odporny na fire.',
    accessQuest: 'Jeden z bossow Forgotten Knowledge Quest.',
    location: 'Zao, Temple Complex.',
    soloLevel: '600+',
    groupLevel: '300+',
    resistances: {
      physical: 0,
      earth: 0,
      fire: -100,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'gold coin', chance: 'very common' },
      { name: 'platinum coin', chance: 'common' },
      { name: 'ultimate health potion', chance: 'common' },
      { name: 'silver token', chance: 'uncommon' },
      { name: 'gold token', chance: 'rare' },
      { name: 'drachaku', chance: 'rare' },
      { name: 'dragon scale helmet', chance: 'very rare' },
      { name: "snake god's sceptre", chance: 'very rare' },
    ],
  },
  {
    name: 'Srezz Yellow Eyes',
    slug: 'Srezz-Yellow-Eyes',
    imageUrl: 'https://static.tibia.com/images/library/creatures/srezz.gif',
    boss: true,
    shortDescription:
      'Serpentowaty boss z Lion Sanctum, grozny glownie przez life drain i solidny earth burst. Nie ma skomplikowanej mechaniki, ale stale obrazenia wysysajace zycie szybko zuzywaja zasoby.',
    accessQuest: 'Czesc Grimvale Quest, etap An Ancient Feud.',
    location: 'Lion Sanctum.',
    soloLevel: '220+',
    groupLevel: '130+',
    attackStyle: ['uderzenia wrecz', 'life drain wave', 'life drain bomb', 'earth ball'],
    resistances: {
      physical: 0,
      earth: -30,
      fire: -30,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: "Srezz' Eye", chance: 'very common' },
      { name: 'platinum coin', chance: 'common' },
      { name: 'ultimate health potion', chance: 'common' },
      { name: 'snake skin', chance: 'common' },
      { name: 'mastermind potion', chance: 'uncommon' },
      { name: 'gemmed figurine', chance: 'uncommon' },
      { name: 'winged tail', chance: 'rare' },
      { name: 'glacier robe', chance: 'rare' },
    ],
  },
  {
    name: 'Tentugly',
    slug: 'Tentugly',
    imageUrl: 'https://static.tibia.com/images/library/creatures/fakeseamonster.gif',
    boss: true,
    shortDescription:
      "Morski boss z A Pirate's Tail Quest, w praktyce walczony jako glowa Tentuglyego wspierana przez macki. Sam sie nie porusza, ale doklada energy i wymaga szybkiego focusu po pojawieniu sie.",
    accessQuest: "Jeden z bossow A Pirate's Tail Quest.",
    location: 'Lodz miedzy Rascacoon a The Wreckoning.',
    soloLevel: '350+',
    groupLevel: '220+',
    attackStyle: [
      'uderzenia wrecz',
      'thunderstorm',
      'energy wave',
      'walka wspierana przez tentacles',
    ],
    resistances: {
      physical: 0,
      earth: 50,
      fire: 25,
      ice: 0,
      energy: -30,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'pirate coin', chance: 'very common' },
      { name: 'platinum coin', chance: 'common' },
      { name: 'ultimate mana potion', chance: 'common' },
      { name: 'ultimate health potion', chance: 'common' },
      { name: "Tentugly's Eye", chance: 'uncommon' },
      { name: 'small treasure chest', chance: 'uncommon' },
      { name: "Tentugly's Jaws", chance: 'rare' },
      { name: 'Plushie of Tentugly', chance: 'very rare' },
    ],
  },
  {
    name: 'Thaian',
    slug: 'Thaian',
    imageUrl: 'https://static.tibia.com/images/library/creatures/thaian.gif',
    boss: true,
    shortDescription:
      'Boss z Feaster of Souls o ekstremalnie wysokich redukcjach na wszystkie typy obrazen. Najwiekszym problemem jest dlugosc walki i koniecznosc utrzymania stalego dps mimo jego twardosci.',
    accessQuest: 'Czesc Feaster of Souls Quest.',
    location: 'Barren Drift.',
    soloLevel: '700+',
    groupLevel: '350+',
    attackStyle: ['uderzenia wrecz', 'bardzo wysoka wytrzymalosc'],
    resistances: {
      physical: -75,
      earth: -75,
      fire: -75,
      ice: -75,
      energy: -75,
      holy: -75,
      death: -75,
    },
    loot: [
      { name: 'green gem', chance: 'common' },
      { name: 'yellow gem', chance: 'common' },
      { name: 'blue gem', chance: 'uncommon' },
      { name: 'phantasmal hair', chance: 'uncommon' },
      { name: 'death toll', chance: 'rare' },
      { name: 'eye of the chasm', chance: 'rare' },
      { name: 'luminescent crystal pickaxe', chance: 'rare' },
      { name: 'pair of old bracers', chance: 'rare' },
    ],
  },
  {
    name: 'The Blazing Rose',
    slug: 'The-Blazing-Rose',
    imageUrl: 'https://static.tibia.com/images/library/creatures/blazingrose.gif',
    boss: true,
    shortDescription:
      'Asuri boss z The Secret Library Quest, opisany na wiki bardzo skromnie. Najpewniejsza informacja to calkowita odpornosc na fire i osadzenie walki w Asura Palace.',
    accessQuest: 'Czesc The Secret Library Quest.',
    location: 'Asura Palace.',
    soloLevel: '300+',
    groupLevel: '180+',
    resistances: {
      physical: 0,
      earth: 0,
      fire: -100,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'platinum coin', chance: 'common' },
      { name: 'great spirit potion', chance: 'common' },
      { name: 'demonic essence', chance: 'common' },
      { name: 'golden lotus brooch', chance: 'uncommon' },
      { name: 'moonlight rod', chance: 'uncommon' },
      { name: 'ultimate health potion', chance: 'common' },
      { name: 'oriental shoes', chance: 'uncommon' },
    ],
  },
  {
    name: 'The Brainstealer',
    slug: 'The-Brainstealer',
    imageUrl: 'https://static.tibia.com/images/library/creatures/brainstealer.gif',
    boss: true,
    shortDescription:
      'Finalny boss Too Hot to Handle Quest, oparty o mocne life drainy i mechanike Madness. Walka wymaga dobrej pozycji, bo beam boli bardzo mocno, a Mental Nexus robi fazy niewrazliwosci.',
    accessQuest: 'Finalny boss Too Hot to Handle Quest.',
    location: 'Dwelling of the Forgotten.',
    soloLevel: '1000+',
    groupLevel: '500+',
    attackStyle: [
      'uderzenia wrecz',
      'life drain beam',
      'death ring',
      'fazy niewrazliwosci z Mental Nexus',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: -100,
    },
    loot: [
      { name: "Brainstealer's Tissue", chance: 'common' },
      { name: 'eldritch crystal', chance: 'uncommon' },
      { name: "Brainstealer's Brain", chance: 'rare' },
      { name: "Brainstealer's Brainwave", chance: 'rare' },
      { name: 'eldritch bow', chance: 'rare' },
      { name: 'eldritch hood', chance: 'rare' },
      { name: 'gilded eldritch wand', chance: 'very rare' },
      { name: 'eldritch monk boots', chance: 'rare' },
    ],
  },
  {
    name: 'The Diamond Blossom',
    slug: 'The-Diamond-Blossom',
    imageUrl: 'https://static.tibia.com/images/library/creatures/diamondblossom.gif',
    boss: true,
    shortDescription:
      'Asuri boss z The Secret Library Quest, o slabiej opisanej walce niz wiekszosc nowoczesnych bossow. Z pewnych danych wynika jedynie, ze lepiej znosi death niz pozostale zywioly i przebywa w Asura Palace.',
    accessQuest: 'Czesc The Secret Library Quest.',
    location: 'Asura Palace.',
    soloLevel: '300+',
    groupLevel: '180+',
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: -30,
    },
    loot: [
      { name: 'platinum coin', chance: 'common' },
      { name: 'soul orb', chance: 'common' },
      { name: 'demonic essence', chance: 'common' },
      { name: 'great spirit potion', chance: 'common' },
      { name: 'golden lotus brooch', chance: 'uncommon' },
      { name: 'moonlight rod', chance: 'uncommon' },
      { name: 'ultimate health potion', chance: 'common' },
    ],
  },
  {
    name: 'The Dread Maiden',
    slug: 'The-Dread-Maiden',
    imageUrl: 'https://static.tibia.com/images/library/creatures/dreadmaiden.gif',
    boss: true,
    shortDescription:
      'Boss z Feaster of Souls, ktory trzeba oslabic przez prowadzenie kolorowych duchow do odpowiednich vorteksow. Zla obsluga tej mechaniki leczy bossa albo karze druzyne dodatkowymi obrazeniami.',
    accessQuest: 'Czesc Feaster of Souls Quest.',
    location: 'Zarganash.',
    soloLevel: '1000+',
    groupLevel: '500+',
    attackStyle: ['uderzenia wrecz', 'mechanika kolorowych duchow', 'oslabianie przez vorteksy'],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 25,
      ice: 0,
      energy: 0,
      holy: 0,
      death: -100,
    },
    loot: [
      { name: 'crystal coin', chance: 'common' },
      { name: 'supreme health potion', chance: 'common' },
      { name: 'ultimate spirit potion', chance: 'common' },
      { name: 'death toll', chance: 'uncommon' },
      { name: 'soulforged lantern', chance: 'rare' },
      { name: 'spooky hood', chance: 'rare' },
      { name: 'pair of nightmare boots', chance: 'rare' },
      { name: 'ghost claw', chance: 'rare' },
    ],
  },
  {
    name: 'The Enraged Thorn Knight',
    slug: 'The-Enraged-Thorn-Knight',
    imageUrl: 'https://static.tibia.com/images/library/creatures/thornknight.gif',
    boss: true,
    shortDescription:
      'Jedna z form Thorn Knighta w Forgotten Knowledge, wygladajaca jak Crystal Warlord. Najwazniejsza zasada walki to calkowite unikanie death damage, bo boss leczy wtedy wielokrotnosc otrzymanych obrazen.',
    accessQuest: 'Jeden z bossow Forgotten Knowledge Quest, dostepny przez Desecrated Glade.',
    location: 'Loch dostepny przez Desecrated Glade.',
    soloLevel: '400+',
    groupLevel: '250+',
    attackStyle: ['uderzenia wrecz', 'presja fizyczna', 'kara za death damage'],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: -100,
    },
    loot: [
      { name: 'gold coin', chance: 'very common' },
      { name: 'platinum coin', chance: 'common' },
      { name: 'great mana potion', chance: 'common' },
      { name: 'ultimate health potion', chance: 'common' },
      { name: 'silver token', chance: 'uncommon' },
      { name: 'gold token', chance: 'rare' },
      { name: 'thorn seed', chance: 'rare' },
      { name: 'ruthless axe', chance: 'rare' },
    ],
  },
];
