export const TIBIA_FANDOM_BATCH_6 = [
  {
    name: 'The False God',
    slug: 'The-False-God',
    imageUrl: 'https://static.tibia.com/images/library/creatures/falsegod.gif',
    boss: true,
    shortDescription:
      'Mocny minotaurzy boss z Cults of Tibia, oparty glownie na melee i presji obszarowej. Najwazniejsza mechanika walki to ciagly ruch po sali i unikanie Sphere of Wrath.',
    accessQuest: 'Czesc Cults of Tibia Quest.',
    location: 'Kryjowka kultu minotaurow niedaleko Mintwallin.',
    soloLevel: '350+',
    groupLevel: '220+',
    attackStyle: [
      'mocne uderzenia wrecz',
      'kamienna fala fizyczna',
      'presja obszarowa',
      'gonienie po arenie',
    ],
    resistances: { physical: -30, earth: 0, fire: -30, ice: 0, energy: -30, holy: 0, death: -75 },
    loot: [
      { name: 'Gold Coin', chance: 'very common' },
      { name: 'Necromantic Rust', chance: 'very common' },
      { name: 'Mysterious Remains', chance: 'very common' },
      { name: 'Great Mana Potion', chance: 'common' },
      { name: 'Ultimate Health Potion', chance: 'common' },
      { name: 'Maimer', chance: 'rare' },
      { name: 'Ornate Mace', chance: 'rare' },
      { name: 'Blood of the Mountain', chance: 'very rare' },
    ],
  },
  {
    name: 'The Fear Feaster',
    slug: 'The-Fear-Feaster',
    imageUrl: 'https://static.tibia.com/images/library/creatures/fearfeaster.gif',
    boss: true,
    shortDescription:
      'Nieumarla bestia z Feaster of Souls, ktora lubi cisnac walke w zwarciu. Jest wyraznie slabsza na physical, fire i energy, ale death zamiast szkodzic moze ja podleczyc.',
    accessQuest: 'Czesc Feaster of Souls Quest.',
    location: 'Zarganash.',
    soloLevel: '700+',
    groupLevel: '450+',
    attackStyle: [
      'uderzenia wrecz',
      'wysoki burst w zwarciu',
      'brak odwrotu',
      'presja pod boss room',
    ],
    resistances: { physical: 25, earth: -30, fire: 25, ice: 0, energy: 25, holy: 0, death: -100 },
    loot: [
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'White Gem', chance: 'uncommon' },
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Ultimate Spirit Potion', chance: 'common' },
      { name: 'Ultimate Mana Potion', chance: 'common' },
      { name: 'Soulforged Lantern', chance: 'rare' },
      { name: 'Ghost Chestplate', chance: 'rare' },
      { name: 'Spooky Hood', chance: 'rare' },
    ],
  },
  {
    name: 'The Flaming Orchid',
    slug: 'The-Flaming-Orchid',
    imageUrl: 'https://static.tibia.com/images/library/creatures/flamingorchid.gif',
    boss: true,
    shortDescription:
      'Asuryjski boss z Asura Palace, ktory miesza fire, death i mana drain. Potrafi paralizowac, znikac i leczyc sie, wiec walka robi sie grozna dla postaci bez ochrony na zywioly.',
    accessQuest:
      'Boss z Asura Palace Quest; wejscie co 20 godzin po zabiciu 3 Cave Hydr i 2 Greater Fire Elementals.',
    location: 'Asura Palace.',
    soloLevel: '250+',
    groupLevel: '180+',
    attackStyle: [
      'uderzenia wrecz',
      'beam z mana drainem',
      'pociski fire i death',
      'paralizujaca chmura',
      'niewidzialnosc i leczenie',
    ],
    resistances: { physical: 0, earth: 0, fire: -100, ice: 25, energy: 0, holy: 0, death: -30 },
    loot: [
      { name: 'Gold Coin', chance: 'common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Great Mana Potion', chance: 'common' },
      { name: 'Ultimate Health Potion', chance: 'common' },
      { name: 'Golden Lotus Brooch', chance: 'uncommon' },
      { name: 'Moonlight Rod', chance: 'uncommon' },
      { name: 'Assassin Dagger', chance: 'uncommon' },
      { name: 'Violet Gem', chance: 'uncommon' },
    ],
  },
  {
    name: 'The Gravedigger',
    slug: 'The-Gravedigger',
    imageUrl: 'https://static.tibia.com/images/library/creatures/thegravedigger.gif',
    boss: true,
    shortDescription:
      'Boss z The Roost of the Graveborn Quest, ktory stoi blisko celu, rzuca mocne fire balle i dorzuca przywolania Bonelord Totemow. Dodatkowo ignoruje Challenge i zwykle skupia sie na najblizszym graczu.',
    accessQuest:
      'Czesc The Roost of the Graveborn Quest; cooldown mozna resetowac itemem Shrunken Head, a Deathly Crypt Rune wypada dopiero po pelnym ukonczeniu questa.',
    location: 'Wejscie do sali na dzwignie znajduje sie na pustyni Ankrahmun.',
    soloLevel: '800+',
    groupLevel: '450+',
    attackStyle: [
      'uderzenia wrecz',
      'fire balle',
      'przywolania Bonelord Totemow',
      'focus najblizszego celu',
    ],
    resistances: { physical: 0, earth: 0, fire: 0, ice: 0, energy: 0, holy: 0, death: 0 },
    loot: [
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'Great Spirit Potion', chance: 'common' },
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Ultimate Mana Potion', chance: 'common' },
      { name: 'Bonelord Shield', chance: 'uncommon' },
      { name: 'Shrunken Head', chance: 'uncommon' },
      { name: 'Grave Flower', chance: 'uncommon' },
      { name: 'Deathly Crypt Rune', chance: 'rare' },
    ],
  },
  {
    name: 'The Lily Of Night',
    slug: 'The-Lily-Of-Night',
    imageUrl: 'https://static.tibia.com/images/library/creatures/lilyofnight.gif',
    boss: true,
    shortDescription:
      'Slabo opisana bosska powiazana z Secret Library, ale z dostepna lista lootu i wyrazna odpornoscia na death. Z uwagi na skape dane z wiki najlepiej traktowac ja jako asuryjskiego archfoe z neutralnymi pozostalymi zywiolami.',
    accessQuest: 'Powiazana z The Secret Library Quest.',
    location: 'Asura Palace.',
    soloLevel: '500+',
    groupLevel: '300+',
    resistances: { physical: 0, earth: 0, fire: 0, ice: 0, energy: 0, holy: 0, death: -100 },
    loot: [
      { name: 'Gold Coin', chance: 'very common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Great Spirit Potion', chance: 'common' },
      { name: 'Assassin Star', chance: 'common' },
      { name: 'Demonic Essence', chance: 'uncommon' },
      { name: 'Golden Lotus Brooch', chance: 'uncommon' },
      { name: 'Moonlight Rod', chance: 'uncommon' },
      { name: 'Necrotic Rod', chance: 'uncommon' },
    ],
  },
  {
    name: 'The Mega Magmaoid',
    slug: 'The-Mega-Magmaoid',
    imageUrl: 'https://static.tibia.com/images/library/creatures/megamagmaoid.gif',
    boss: true,
    shortDescription:
      'Pyro-elementalny boss z Too Hot to Handle Quest. Jest odporny na earth, wzmacnia go fire i ma widoczna slabosc na death, ale wiki nie podaje jeszcze wiarygodnej tabeli lootu.',
    accessQuest: 'Czesc Too Hot to Handle Quest.',
    location: 'Dwelling of the Forgotten.',
    soloLevel: '350+',
    groupLevel: '220+',
    resistances: { physical: 0, earth: -100, fire: -100, ice: 0, energy: -30, holy: 0, death: 25 },
  },
  {
    name: 'The Monster',
    slug: 'The-Monster',
    imageUrl: 'https://static.tibia.com/images/library/creatures/themonster.gif',
    boss: true,
    shortDescription:
      'Finalowy eksperyment Doctor Marrow z Cradle of Monsters. Na starcie jest praktycznie niewrazliwy i trzeba oslabic go, przeciagajac po rozlanych odczynnikach z niszczonych pojemnikow.',
    accessQuest: 'Final boss The Cradle of Monsters Quest.',
    location: 'Deeper Ingol.',
    soloLevel: '500+',
    groupLevel: '300+',
    attackStyle: ['uderzenia wrecz', 'hex', 'rzadki retarget', 'mechanika oslabiania pojemnikami'],
    resistances: { physical: 0, earth: 0, fire: 0, ice: 0, energy: 0, holy: 0, death: 0 },
    loot: [
      { name: 'Platinum Coin', chance: 'very common' },
      { name: 'Ultimate Health Potion', chance: 'common' },
      { name: 'Ultimate Mana Potion', chance: 'common' },
      { name: 'Yellow Gem', chance: 'common' },
      { name: 'Giant Amethyst', chance: 'semi-rare' },
      { name: 'Watermelon Tourmaline', chance: 'rare' },
      { name: "Alchemist's Notepad", chance: 'very rare' },
      { name: 'Mutated Skin Armor', chance: 'very rare' },
    ],
  },
  {
    name: 'The Moonlight Aster',
    slug: 'The-Moonlight-Aster',
    imageUrl: 'https://static.tibia.com/images/library/creatures/moonlightaster.gif',
    boss: true,
    shortDescription:
      'Asuryjski boss z wyraznym pakietem kontroli: mana drain, curse, paraliza, niewidzialnosc i samoleczenie. Walka jest podobna do Flaming Orchid, ale mocniej karze slabosci na earth i energy.',
    accessQuest:
      'Boss z Asura Palace Quest; wejscie co 20 godzin po zabiciu 2 Vicious Liches i 2 Vile Destroyerow.',
    location: 'Asura Palace.',
    soloLevel: '250+',
    groupLevel: '180+',
    attackStyle: [
      'uderzenia wrecz',
      'beam z mana drainem',
      'kulka death z curse',
      'paralizujaca chmura',
      'niewidzialnosc i leczenie',
    ],
    resistances: { physical: 0, earth: 25, fire: -30, ice: -30, energy: 25, holy: 0, death: -100 },
    loot: [
      { name: 'Gold Coin', chance: 'common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Ultimate Health Potion', chance: 'common' },
      { name: 'Great Mana Potion', chance: 'common' },
      { name: 'Moonlight Rod', chance: 'uncommon' },
      { name: 'Peacock Feather Fan', chance: 'uncommon' },
      { name: 'Skullcracker Armor', chance: 'rare' },
      { name: 'Spellbook of Mind Control', chance: 'rare' },
    ],
  },
  {
    name: 'The Moonsnow Magnolia',
    slug: 'The-Moonsnow-Magnolia',
    imageUrl: 'https://static.tibia.com/images/library/creatures/moonsnowmagnolia.gif',
    boss: true,
    shortDescription:
      'Boss z Shards of a Broken Moon Quest, o slabo opisanej mechanice, ale dobrze udokumentowanych nagrodach. Zle znosi earth, fire i energy, a najlepiej broni sie przed ice.',
    accessQuest:
      'Czesc Shards of a Broken Moon Quest; cooldown mozna resetowac Frozen Peacock Feather.',
    location: 'Asura Citadel.',
    soloLevel: '700+',
    groupLevel: '450+',
    resistances: { physical: 0, earth: 25, fire: 25, ice: -30, energy: 25, holy: 0, death: 0 },
    loot: [
      { name: 'Enchanted Flamingo Amulet of Destruction', chance: 'rare' },
      { name: 'Enchanted Flamingo Amulet of Nature', chance: 'rare' },
      { name: 'Enchanted Flamingo Amulet of Precision', chance: 'rare' },
      { name: 'Enchanted Flamingo Amulet of Valor', chance: 'rare' },
      { name: 'Enchanted Swan Amulet of Balance', chance: 'rare' },
    ],
  },
  {
    name: 'The Nightmare Beast',
    slug: 'The-Nightmare-Beast',
    imageUrl: 'https://static.tibia.com/images/library/creatures/nightmarebeast.gif',
    boss: true,
    shortDescription:
      'Final boss Dream Courts z bardzo mocnymi atakami death na dystans. Kluczem do walki jest rotacyjne uzywanie totemu i tworzenie Dream Catcherow, aby zdejmowac curse z druzyny.',
    accessQuest: 'Final boss The Dream Courts Quest.',
    location: 'Dream Scar.',
    soloLevel: '700+',
    groupLevel: '450+',
    attackStyle: [
      'ataki dystansowe death',
      'death beam i chain',
      'czesty retarget',
      'mechanika curse z Dream Catcherami',
    ],
    resistances: { physical: -30, earth: 0, fire: -30, ice: 0, energy: 0, holy: -30, death: 0 },
    loot: [
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Ultimate Spirit Potion', chance: 'common' },
      { name: 'Ultimate Mana Potion', chance: 'common' },
      { name: 'Silver Token', chance: 'uncommon' },
      { name: 'Gold Token', chance: 'uncommon' },
      { name: "Beast's Nightmare-Cushion", chance: 'rare' },
      { name: 'Turquoise Tendril Lantern', chance: 'rare' },
      { name: 'Dark Whispers', chance: 'rare' },
    ],
  },
  {
    name: 'The Pale Worm',
    slug: 'The-Pale-Worm',
    imageUrl: 'https://static.tibia.com/images/library/creatures/paleworm.gif',
    boss: true,
    shortDescription:
      'Koncowy boss Feaster of Souls, dzielacy pule zycia z A Weak Spot. Jest bardzo odporny na praktycznie kazdy zywiol i odpowiada poteznym melee, poison, death oraz holy.',
    accessQuest: 'Final boss Feaster of Souls Quest, ze wspolna pula zycia z A Weak Spot.',
    location: 'Zarganash.',
    soloLevel: '1000+',
    groupLevel: '600+',
    attackStyle: [
      'bardzo mocne uderzenia wrecz',
      'poison gfb',
      'death wave',
      'holy beam',
      'wspolna pula zycia z A Weak Spot',
    ],
    resistances: {
      physical: -75,
      earth: -75,
      fire: -75,
      ice: -75,
      energy: -75,
      holy: -75,
      death: -75,
    },
    loot: [
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'Ultimate Spirit Potion', chance: 'common' },
      { name: "Pale Worm's Scalp", chance: 'rare' },
      { name: 'Ring of Souls', chance: 'rare' },
      { name: 'Ghost Backpack', chance: 'rare' },
      { name: 'Phantasmal Axe', chance: 'rare' },
      { name: 'Pair of Nightmare Boots', chance: 'rare' },
      { name: 'Fabulous Legs', chance: 'very rare' },
    ],
  },
  {
    name: 'The Rootkraken',
    slug: 'The-Rootkraken',
    imageUrl: 'https://static.tibia.com/images/library/creatures/rootkraken.gif',
    boss: true,
    shortDescription:
      'Finalowy boss Podzilla Quest, ktory miesza root, earth, death i holy. Najwiekszym zagrozeniem sa strefy kontroli i utrudnianie ruchu, a nie sam prosty burst z jednego zywiolu.',
    accessQuest: 'Final boss Podzilla Quest.',
    location: 'Podzilla.',
    soloLevel: '600+',
    groupLevel: '350+',
    attackStyle: ['root', 'strefy earth i death', 'holy obszarowki', 'death strike'],
    resistances: { physical: 0, earth: 25, fire: 50, ice: 0, energy: -30, holy: 0, death: 0 },
    loot: [
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Ultimate Health Potion', chance: 'common' },
      { name: 'Great Mana Potion', chance: 'common' },
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Amber Crusher', chance: 'uncommon' },
      { name: 'Root Tentacle', chance: 'uncommon' },
      { name: 'Strange Inedible Fruit', chance: 'uncommon' },
      { name: 'Amber Kusarigama', chance: 'rare' },
    ],
  },
  {
    name: 'The Sandking',
    slug: 'The-Sandking',
    imageUrl: 'https://static.tibia.com/images/library/creatures/sandkingfinal.gif',
    boss: true,
    shortDescription:
      'Pustynny boss z Cults of Tibia, ktory miesza melee, chainy i obszarowe trucizny. Kluczowe jest niedopuszczenie, by wchodzil na zwloki Sand Broodow, bo wtedy mocno sie leczy.',
    accessQuest: 'Czesc Cults of Tibia Quest.',
    location: 'Pod Dark Pyramid.',
    soloLevel: '350+',
    groupLevel: '220+',
    attackStyle: [
      'mocne uderzenia wrecz',
      'fala poison/energy',
      'death chain',
      'leczenie na zwlokach Sand Brood',
    ],
    resistances: { physical: 0, earth: 0, fire: 0, ice: 0, energy: 0, holy: 0, death: 0 },
    loot: [
      { name: 'Gold Coin', chance: 'very common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Great Mana Potion', chance: 'common' },
      { name: 'Ultimate Health Potion', chance: 'common' },
      { name: 'Silver Token', chance: 'uncommon' },
      { name: 'Gold Token', chance: 'uncommon' },
      { name: 'Cobra Crown', chance: 'rare' },
      { name: 'Calopteryx Cape', chance: 'rare' },
    ],
  },
  {
    name: 'The Scourge Of Oblivion',
    slug: 'The-Scourge-Of-Oblivion',
    imageUrl: 'https://static.tibia.com/images/library/creatures/scourgeofoblivion00.gif',
    boss: true,
    shortDescription:
      'Finalowy boss Secret Library z wielofazowa walka i okresami niewrazliwosci. Podczas invul faz trzeba czyscic summony i przetrwac mieszanke fire, physical oraz death.',
    accessQuest: 'Final battle The Secret Library Quest.',
    location: 'Secret Library.',
    soloLevel: '1200+',
    groupLevel: '700+',
    attackStyle: [
      'fazy niewrazliwosci',
      'great wave fire',
      'beam fizyczny',
      'death ball i chain',
      'przywolania podczas walki',
    ],
    resistances: { physical: 0, earth: 0, fire: 0, ice: 0, energy: 0, holy: 0, death: 0 },
    loot: [
      { name: 'Royal Star', chance: 'common' },
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'Ultimate Spirit Potion', chance: 'common' },
      { name: 'Silver Token', chance: 'common' },
      { name: 'Gold Token', chance: 'uncommon' },
      { name: 'Spark Sphere', chance: 'uncommon' },
      { name: 'Library Ticket', chance: 'rare' },
      { name: 'The Calamity', chance: 'very rare' },
    ],
  },
  {
    name: 'The Souldespoiler',
    slug: 'The-Souldespoiler',
    imageUrl: 'https://static.tibia.com/images/library/creatures/souldespoiler.gif',
    boss: true,
    shortDescription:
      'Cults of Tibia boss, ktory realnie traci zycie glownie dzieki Freed Soulom. Sam zadaje glownie physical i death, ale walka jest bardziej o obsluge mechaniki summonow niz o czysty dps.',
    accessQuest: 'Czesc Cults of Tibia Quest.',
    location: 'Kryjowka Humans Cult pod Outlaw Camp.',
    soloLevel: '350+',
    groupLevel: '220+',
    attackStyle: [
      'uderzenia wrecz',
      'death bomb i death strike',
      'spawn Freed Souls',
      'mechanika zabijania przez summony',
    ],
    resistances: { physical: 0, earth: 0, fire: 0, ice: 0, energy: -30, holy: 0, death: 0 },
    loot: [
      { name: 'Gold Coin', chance: 'very common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Mysterious Remains', chance: 'common' },
      { name: 'Ultimate Health Potion', chance: 'common' },
      { name: 'Curious Matter', chance: 'uncommon' },
      { name: 'Spark Sphere', chance: 'uncommon' },
      { name: 'Shield of Corruption', chance: 'rare' },
      { name: 'Rift Lance', chance: 'rare' },
    ],
  },
  {
    name: 'The Source Of Corruption',
    slug: 'The-Source-Of-Corruption',
    imageUrl: 'https://static.tibia.com/images/library/creatures/sourceofcorruption.gif',
    boss: true,
    shortDescription:
      'Elektro-elementalny final boss Cults of Tibia. Walczy w zwarciu, rzuca energy beam, przywoluje Soul Reapery i odbija czesc otrzymanych obrazen, wiec shooterzy musza pilnowac hp.',
    accessQuest: 'Final boss Cults of Tibia Quest.',
    location: 'Feyrist, za teleportem obok Gerimor.',
    soloLevel: '450+',
    groupLevel: '280+',
    attackStyle: [
      'uderzenia wrecz',
      'energy beam',
      'odbicie czesci obrazen',
      'przywolania Soul Reaperow',
    ],
    resistances: { physical: 0, earth: 0, fire: 0, ice: 0, energy: 0, holy: 0, death: 0 },
    loot: [
      { name: 'Gold Coin', chance: 'very common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Crystallized Anger', chance: 'common' },
      { name: 'Solid Rage', chance: 'common' },
      { name: 'Gold Token', chance: 'uncommon' },
      { name: 'Silver Token', chance: 'uncommon' },
      { name: 'Umbral Slayer', chance: 'rare' },
      { name: 'Rift Bow', chance: 'rare' },
    ],
  },
];
