export const TIBIA_FANDOM_BATCH_2 = [
  {
    name: 'Darkfang',
    slug: 'Darkfang',
    imageUrl: 'https://static.tibia.com/images/library/creatures/darkfang.gif',
    boss: true,
    shortDescription:
      'Wilkolaczy boss z Grimvale, walczacy glownie w zwarciu i wspierajacy sie przywolaniami. Najwieksze zagrozenie robi, gdy summonowane wilki zaczynaja dokladac obrazenia obok jego falowego ataku.',
    accessQuest:
      'Teleport w jaskini werebestii na Edron w trakcie Grimvale Quest (The Curse Spreads).',
    location: 'Edron, po teleporcie wewnatrz jaskini werebestii.',
    soloLevel: '130+',
    groupLevel: '80+',
    attackStyle: ['uderzenia wrecz', 'przywolania gloom wolfow', 'falowy atak obszarowy'],
    resistances: {
      physical: 0,
      earth: -75,
      fire: 25,
      ice: -75,
      energy: -75,
      holy: 0,
      death: -75,
    },
    loot: [
      { name: 'gold coin', chance: 'very common' },
      { name: 'platinum coin', chance: 'very common' },
      { name: 'black pearl', chance: 'common' },
      { name: 'werewolf fur', chance: 'common' },
      { name: 'werewolf fangs', chance: 'common' },
      { name: 'stone skin amulet', chance: 'uncommon' },
      { name: 'silver token', chance: 'rare' },
      { name: 'dreaded cleaver', chance: 'rare' },
    ],
  },
  {
    name: 'Deathstrike',
    slug: 'Deathstrike',
    imageUrl: 'https://static.tibia.com/images/library/creatures/deathstrike.gif',
    boss: true,
    shortDescription:
      "Warzone'owy geo-elemental z bardzo mocnym melee, niewidzialnoscia i czestym leczeniem. Walka dluzy sie przez jego self-heal, wiec potrzebuje stalej presji i sensownego focusu druzyny.",
    accessQuest: "Wymagany dostep do Warzone 1 w Bigfoot's Burden oraz wejscie do sali bossa.",
    location: 'Warzone 1.',
    soloLevel: '700+',
    groupLevel: '250+',
    attackStyle: [
      'mocne uderzenia wrecz',
      'mana drain wave',
      'fire beam i energy missile',
      'niewidzialnosc oraz samoleczenie',
    ],
    resistances: {
      physical: -75,
      earth: -100,
      fire: -75,
      ice: -75,
      energy: -75,
      holy: -75,
      death: -75,
    },
    loot: [
      { name: "deathstrike's snippet", chance: 'very common' },
      { name: 'crystal crossbow', chance: 'uncommon' },
      { name: 'crystalline axe', chance: 'uncommon' },
      { name: 'crystalline sword', chance: 'uncommon' },
      { name: 'mycological bow', chance: 'uncommon' },
      { name: 'mycological mace', chance: 'uncommon' },
      { name: 'shiny blade', chance: 'uncommon' },
      { name: 'decorative ribbon', chance: 'semi-rare' },
    ],
  },
  {
    name: 'Dragon Pack',
    slug: 'Dragon-Pack',
    imageUrl: 'https://static.tibia.com/images/library/creatures/representingdespor.gif',
    boss: true,
    shortDescription:
      'To nie klasyczny pojedynczy boss, lecz reprezentacja Dragon Hoard z finalu 20 Years a Cook Quest. Sam cel jest nieosiagalny, a zagrozenie pochodzi od ostatniego smoka, z ktorym dzieli pule zycia.',
    accessQuest:
      'Pojawia sie tylko w finalnej walce 20 Years a Cook Quest po ubiciu siedmiu smokow.',
    location: 'Sala finalna Dragon Hoard w 20 Years a Cook Quest.',
    soloLevel: '900+',
    groupLevel: '400+',
    attackStyle: [
      'brak bezposrednich atakow',
      'dzielona pula hp z ostatnim smokiem',
      'zagrozenia zalezne od aktywnego smoka',
    ],
    resistances: {
      physical: -100,
      earth: -100,
      fire: -100,
      ice: -100,
      energy: -100,
      holy: -100,
      death: -100,
    },
    loot: [
      { name: 'gold-scaled sentinel', chance: 'semi-rare' },
      { name: 'arcane dragon robe', chance: 'rare' },
      { name: 'mystical dragon robe', chance: 'rare' },
      { name: 'dauntless dragon scale armor', chance: 'rare' },
      { name: 'unerring dragon scale armor', chance: 'rare' },
      { name: 'heralds insignia', chance: 'very rare' },
      { name: 'heralds wings', chance: 'very rare' },
      { name: 'merudri battle mail', chance: 'very rare' },
    ],
  },
  {
    name: 'Drume',
    slug: 'Drume',
    imageUrl: 'https://static.tibia.com/images/library/creatures/drume.gif',
    boss: true,
    shortDescription:
      'Uzurpator z Order of the Lion walczacy w zwarciu, ale dorzucajacy mocne earth i death. Dodatkowe ryzyko daja jego przywolania, wiec walka robi sie niebezpieczna, gdy zespol traci kontrole nad polem.',
    accessQuest:
      'Boss z The Order of the Lion Quest, odblokowywany podczas watku uzurpatorow w Bounac.',
    location: 'Bounac, pola na poludniowy wschod od miasta.',
    soloLevel: '400+',
    groupLevel: '250+',
    attackStyle: [
      'uderzenia wrecz',
      'earth strike i trucizna',
      'death projectile',
      'przywolania rycerzy zakonu',
    ],
    resistances: {
      physical: -75,
      earth: -100,
      fire: 0,
      ice: 0,
      energy: 25,
      holy: 25,
      death: -75,
    },
    loot: [
      { name: 'royal star', chance: 'very common' },
      { name: 'ultimate mana potion', chance: 'common' },
      { name: 'supreme health potion', chance: 'common' },
      { name: 'bullseye potion', chance: 'common' },
      { name: 'silver token', chance: 'uncommon' },
      { name: 'lion amulet', chance: 'rare' },
      { name: 'lion spellbook', chance: 'rare' },
      { name: 'lion plate', chance: 'rare' },
    ],
  },
  {
    name: 'Duke Krule',
    slug: 'Duke-Krule',
    imageUrl: 'https://static.tibia.com/images/library/creatures/dukekrule.gif',
    boss: true,
    shortDescription:
      'Undead boss z Grave Danger, ktory sam nie jest najgorszy, ale jego summony i mechanika ognia oraz wody potrafia skasowac nieustawiona druzyne. Gracze z rozna przemiana nie powinni podchodzic do siebie, bo dostaja bardzo wysoki burst.',
    accessQuest: 'Wymagany postep w Grave Danger Quest i wejscie do instancji pod Ancient Temple.',
    location: 'Pod Ancient Temple pod Thais.',
    soloLevel: '900+',
    groupLevel: '450+',
    attackStyle: [
      'uderzenia wrecz',
      'przywolania',
      'obrazenia od efektow ognia i lodu',
      'mechanika przemiany druzyny',
    ],
    resistances: {
      physical: 0,
      earth: -75,
      fire: 25,
      ice: 0,
      energy: -75,
      holy: 0,
      death: -100,
    },
    loot: [
      { name: 'platinum coin', chance: 'common' },
      { name: 'ultimate mana potion', chance: 'common' },
      { name: 'supreme health potion', chance: 'common' },
      { name: 'silver token', chance: 'uncommon' },
      { name: 'young lich worm', chance: 'uncommon' },
      { name: 'rotten heart', chance: 'rare' },
      { name: 'noble amulet', chance: 'rare' },
      { name: 'final judgement', chance: 'very rare' },
    ],
  },
  {
    name: 'Earl Osam',
    slug: 'Earl-Osam',
    imageUrl: 'https://static.tibia.com/images/library/creatures/earlosam.gif',
    boss: true,
    shortDescription:
      'Nekromantyczny boss z Grave Danger oparty o ice i earth. Kluczowy moment walki to faza channelingu, kiedy trzeba blyskawicznie zbijac Magical Spheres, bo kazda kula moze podleczyc go o ogromna ilosc hp.',
    accessQuest: 'Wymagany postep w Grave Danger Quest i dostep do walki na cmentarzu Cormayi.',
    location: 'Cmentarz na Cormayi.',
    soloLevel: '900+',
    groupLevel: '450+',
    attackStyle: [
      'uderzenia wrecz',
      'ice beam i ice chain',
      'earth wave',
      'faza channelingu z leczacymi kulami',
    ],
    resistances: {
      physical: 0,
      earth: -75,
      fire: 25,
      ice: -100,
      energy: 25,
      holy: 0,
      death: -100,
    },
    loot: [
      { name: 'platinum coin', chance: 'common' },
      { name: 'ultimate spirit potion', chance: 'common' },
      { name: 'supreme health potion', chance: 'common' },
      { name: 'silver token', chance: 'uncommon' },
      { name: 'ancient liche bone', chance: 'uncommon' },
      { name: 'rotten heart', chance: 'rare' },
      { name: 'token of love', chance: 'rare' },
      { name: 'final judgement', chance: 'rare' },
    ],
  },
  {
    name: 'Ekatrix',
    slug: 'Ekatrix',
    imageUrl: 'https://static.tibia.com/images/library/creatures/ekatrix.gif',
    boss: true,
    shortDescription:
      'Niski poziomem boss-czarownica z Tainted Souls, walczaca jak mocniejsza Witch. Trzyma dystans, rzuca ogien i zostawia fire fieldy, ale dla przygotowanej postaci nie stanowi duzego zagrozenia.',
    accessQuest: 'Czesc The Tainted Souls Quest, z dostepem do Tainted Caves w Green Claw Swamp.',
    location: 'Tainted Caves w Green Claw Swamp.',
    soloLevel: '80+',
    groupLevel: '40+',
    attackStyle: ['fireball', 'fire field', 'walka na dystans'],
    resistances: {
      physical: 25,
      earth: -75,
      fire: 0,
      ice: 0,
      energy: -100,
      holy: 25,
      death: 0,
    },
    loot: [
      { name: 'gold coin', chance: 'very common' },
      { name: 'cookie', chance: 'common' },
      { name: 'broom', chance: 'common' },
      { name: 'witch broom', chance: 'uncommon' },
      { name: 'necrotic rod', chance: 'uncommon' },
      { name: 'stuffed toad', chance: 'uncommon' },
      { name: 'stealth ring', chance: 'rare' },
      { name: 'witch hat', chance: 'rare' },
    ],
  },
  {
    name: 'Eldritch Dragon Lord',
    slug: 'Eldritch-Dragon-Lord',
    imageUrl: 'https://static.tibia.com/images/library/creatures/eldritchdragonlord.gif',
    boss: true,
    shortDescription:
      'Nowoczesny smok-boss z Roost of the Graveborn, nastawiony na mocna presje i nagrody questowe. Przy skromnych danych na wiki najlepiej traktowac go jak znacznie wzmocnionego Dragon Lorda z wysoka kara za bledy pozycyjne.',
    accessQuest:
      'Czesc The Roost of the Graveborn Quest; cooldown mozna resetowac Golden Claw, a Fiery Crypt Rune wypada dopiero po pelnym ukonczeniu questa.',
    location: 'Pits of Inferno Dragon Lair.',
    soloLevel: '1000+',
    groupLevel: '600+',
    attackStyle: ['mocne ataki ogniowe', 'obrazenia obszarowe smoczego typu', 'uderzenia wrecz'],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'crystal coin', chance: 'common' },
      { name: 'ultimate health potion', chance: 'common' },
      { name: 'dragon tongue', chance: 'common' },
      { name: 'dragonbone staff', chance: 'uncommon' },
      { name: 'dragon shield', chance: 'uncommon' },
      { name: 'dragon slayer', chance: 'uncommon' },
      { name: 'golden claw', chance: 'rare' },
      { name: 'fiery crypt rune', chance: 'rare' },
    ],
  },
  {
    name: 'Eradicator',
    slug: 'Eradicator',
    imageUrl: 'https://static.tibia.com/images/library/creatures/eradicator.gif',
    boss: true,
    shortDescription:
      'Elektryczny boss z Heart of Destruction z bardzo mocnym melee i stalym spamem energy wave oraz beam. Co pewien czas zmienia forme i przywoluje Sparks of Destruction, wiec druzyna musi szybko przelaczac fokus.',
    accessQuest: 'Jeden z bossow Heart of Destruction Quest, wymagajacy dostepu do Otherworldu.',
    location: 'Otherworld.',
    soloLevel: '900+',
    groupLevel: '450+',
    attackStyle: [
      'bardzo mocne uderzenia wrecz',
      'great energy wave',
      'great energy beam',
      'zmiana formy i przywolania spark of destruction',
    ],
    resistances: {
      physical: -75,
      earth: -75,
      fire: -75,
      ice: -75,
      energy: -75,
      holy: -75,
      death: 0,
    },
    loot: [
      { name: 'gold token', chance: 'very common' },
      { name: 'platinum coin', chance: 'common' },
      { name: 'yellow gem', chance: 'common' },
      { name: 'ultimate health potion', chance: 'common' },
      { name: 'spark sphere', chance: 'uncommon' },
      { name: 'mysterious remains', chance: 'uncommon' },
      { name: 'void boots', chance: 'rare' },
      { name: 'plasmatic lightning', chance: 'rare' },
    ],
  },
  {
    name: 'Essence Of Malice',
    slug: 'Essence-Of-Malice',
    imageUrl: 'https://static.tibia.com/images/library/creatures/essenceofmalice.gif',
    boss: true,
    shortDescription:
      'Smoczo-undeadowy boss z Cults of Tibia, bijacy glownie death i walczacy bez szczegolnie skomplikowanej mechaniki. Najwazniejsze to nie opierac dps-u na death i wykorzystywac jego wyrazne slabosci na zywioly.',
    accessQuest: 'Czesc Cults of Tibia Quest, z walka odblokowywana w Forbidden Temple pod Carlin.',
    location: 'Forbidden Temple pod Carlin.',
    soloLevel: '350+',
    groupLevel: '220+',
    attackStyle: ['uderzenia wrecz', 'death missile', 'death beam', 'chain lightning z death'],
    resistances: {
      physical: 0,
      earth: 25,
      fire: 25,
      ice: -75,
      energy: 25,
      holy: 25,
      death: -100,
    },
    loot: [
      { name: 'gold coin', chance: 'very common' },
      { name: 'platinum coin', chance: 'common' },
      { name: 'ultimate health potion', chance: 'common' },
      { name: 'demon shield', chance: 'uncommon' },
      { name: 'shockwave amulet', chance: 'uncommon' },
      { name: 'gold token', chance: 'uncommon' },
      { name: 'blade of corruption', chance: 'rare' },
      { name: 'magma monocle', chance: 'rare' },
    ],
  },
  {
    name: 'Faceless Bane',
    slug: 'Faceless-Bane',
    imageUrl: 'https://static.tibia.com/images/library/creatures/facelessbane.gif',
    boss: true,
    shortDescription:
      'Dream Courtsowy duch-boss, ktory laczy energy, death i life drain oraz doklada trzy typy spectrow naraz. W praktyce trzeba unikac death damage i dobrze zabezpieczyc blockerowi energy/death, bo combo wchodzi niemal co ture.',
    accessQuest:
      'Czesc The Dream Courts Quest (linia Haunted House), z dostepem do Buried Cathedral.',
    location: 'Buried Cathedral.',
    soloLevel: '450+',
    groupLevel: '250+',
    attackStyle: [
      'uderzenia wrecz',
      'energy strike',
      'death strike',
      'beam life drain i przywolania spectrow',
    ],
    resistances: {
      physical: -75,
      earth: 0,
      fire: 25,
      ice: 0,
      energy: 0,
      holy: 0,
      death: -75,
    },
    loot: [
      { name: 'platinum coin', chance: 'common' },
      { name: 'small sapphire', chance: 'common' },
      { name: 'life crystal', chance: 'uncommon' },
      { name: 'violet gem', chance: 'uncommon' },
      { name: 'book backpack', chance: 'rare' },
      { name: 'ectoplasmic shield', chance: 'rare' },
      { name: 'spirit guide', chance: 'rare' },
      { name: 'dream blossom staff', chance: 'rare' },
    ],
  },
  {
    name: 'Ghulosh',
    slug: 'Ghulosh',
    imageUrl: 'https://static.tibia.com/images/library/creatures/ghulosh.gif',
    boss: true,
    shortDescription:
      'Biblioteczny demon z Secret Library z charakterystyczna faza Deathgaze. Walka polega na ustawianiu odbitych beamow w Concentrated Death i jednoczesnym pilnowaniu minionow, bo samo bicie bossa nie wystarczy.',
    accessQuest:
      'Czesc The Secret Library Quest; wejscie przez Fire Section i aktywacja walki przy Ostentatious Bookstand.',
    location: 'Fire Section w Secret Library.',
    soloLevel: '1100+',
    groupLevel: '600+',
    attackStyle: [
      'uderzenia wrecz',
      'death beam i death wave',
      'poison explosion',
      'physical chain i faza deathgaze',
    ],
    resistances: {
      physical: 0,
      earth: 25,
      fire: -100,
      ice: -75,
      energy: -75,
      holy: 25,
      death: -75,
    },
    loot: [
      { name: 'platinum coin', chance: 'common' },
      { name: 'supreme health potion', chance: 'common' },
      { name: 'silver token', chance: 'common' },
      { name: 'knowledgeable book', chance: 'uncommon' },
      { name: 'solid rage', chance: 'uncommon' },
      { name: 'unliving demonbone', chance: 'rare' },
      { name: 'ornate tome', chance: 'rare' },
      { name: 'gold token', chance: 'rare' },
    ],
  },
  {
    name: 'Gnomevil',
    slug: 'Gnomevil',
    imageUrl: 'https://static.tibia.com/images/library/creatures/gnomehorticulist.gif',
    boss: true,
    shortDescription:
      'Warzone 2 boss, relatywnie latwy jak na swoja pule hp, ale z bardzo mocnym melee i paskudnym mana drainem. Najbezpieczniej zamknac go na blokerach, bo wtedy jego beamy i retarget na najwyzszy dps sa duzo latwiejsze do opanowania.',
    accessQuest: "Wymagany dostep do Warzone 2 w Bigfoot's Burden.",
    location: 'Sala bossa w Warzone 2.',
    soloLevel: '650+',
    groupLevel: '250+',
    attackStyle: [
      'mocne uderzenia wrecz',
      'ice i earth strike',
      'mana drain beams',
      'niewidzialnosc i samoleczenie',
    ],
    resistances: {
      physical: -75,
      earth: -100,
      fire: -75,
      ice: -75,
      energy: -100,
      holy: -75,
      death: -75,
    },
    loot: [
      { name: "gnomevil's hat", chance: 'very common' },
      { name: 'crystalline sword', chance: 'uncommon' },
      { name: 'crystal crossbow', chance: 'uncommon' },
      { name: 'crystalline axe', chance: 'uncommon' },
      { name: 'mycological bow', chance: 'uncommon' },
      { name: 'mycological mace', chance: 'uncommon' },
      { name: 'shiny blade', chance: 'uncommon' },
      { name: 'decorative ribbon', chance: 'rare' },
    ],
  },
  {
    name: 'Gorzindel',
    slug: 'Gorzindel',
    imageUrl: 'https://static.tibia.com/images/library/creatures/gorzindel.gif',
    boss: true,
    shortDescription:
      'Demoniczny boss z Secret Library, ktorego najpierw trzeba oslabic przez niszczenie ksiag w osobnych pokojach. Walka mocno premiuje kontrole minionow, szybkie przejscia przez teleport i odporna druzyne na paralize.',
    accessQuest:
      'Czesc The Secret Library Quest; wejscie przez Fire Section i teleport aktywowany Ostentatious Bookstand.',
    location: 'Secret Library.',
    soloLevel: '1200+',
    groupLevel: '650+',
    attackStyle: [
      'mocne czary obszarowe',
      'paraliza',
      'przywolania minionow',
      'mechanika niszczenia ksiag',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: -100,
      ice: 0,
      energy: -75,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'platinum coin', chance: 'common' },
      { name: 'crystal coin', chance: 'common' },
      { name: 'ultimate spirit potion', chance: 'common' },
      { name: 'knowledgeable book', chance: 'uncommon' },
      { name: 'sinister book', chance: 'uncommon' },
      { name: 'ominous book', chance: 'uncommon' },
      { name: 'curious matter', chance: 'rare' },
      { name: 'gold token', chance: 'rare' },
    ],
  },
  {
    name: "Goshnar's Cruelty",
    slug: "Goshnar's-Cruelty",
    imageUrl: 'https://static.tibia.com/images/library/creatures/goshnarscruelty.gif',
    boss: true,
    shortDescription:
      'Soul Warowy boss-duch walczacy przewaznie w zwarciu, ale regularnie mieszajacy fizyczne combosy z life drainem. Nie ma wyraznych slabosci elementarnych, wiec najwazniejsze sa defensy i stabilne utrzymanie pozycji.',
    accessQuest: 'Czesc Soul War Quest; wymagany dostep do Furious Crater i instancji bossa.',
    location: 'Furious Crater.',
    soloLevel: '1600+',
    groupLevel: '800+',
    attackStyle: [
      'uderzenia wrecz',
      'life drain wave',
      'physical chain i dust berserk',
      'krwawe pociski obszarowe',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'ultimate mana potion', chance: 'common' },
      { name: 'crystal coin', chance: 'common' },
      { name: "cruelty's chest", chance: 'rare' },
      { name: "cruelty's claw", chance: 'rare' },
      { name: 'figurine of cruelty', chance: 'rare' },
      { name: 'bag you desire', chance: 'rare' },
      { name: 'spectral saddle', chance: 'very rare' },
      { name: 'spectral horse tack', chance: 'very rare' },
    ],
  },
  {
    name: "Goshnar's Greed",
    slug: "Goshnar's-Greed",
    imageUrl: 'https://static.tibia.com/images/library/creatures/goshnarsgreed.gif',
    boss: true,
    shortDescription:
      'Soul Warowy boss z Mirrored Nightmare, opisany na wiki dosc skromnie, ale traktowany jako dluga i wymagajaca walka endgame. Przy braku oczywistych slabosci najlepiej wejsc z pelnym przygotowaniem defensywnym i mocnym, rownym dps-em.',
    accessQuest: 'Czesc Soul War Quest; wymagany dostep do Mirrored Nightmare i instancji bossa.',
    location: 'Mirrored Nightmare.',
    soloLevel: '1600+',
    groupLevel: '800+',
    attackStyle: [
      'uderzenia wrecz',
      'obrazenia obszarowe',
      'dluga walka na wytrzymalosc',
      'brak wyraznych slabosci elementarnych',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'ultimate mana potion', chance: 'common' },
      { name: 'crystal coin', chance: 'common' },
      { name: 'giant shimmering pearl', chance: 'uncommon' },
      { name: 'figurine of greed', chance: 'rare' },
      { name: "greed's arm", chance: 'rare' },
      { name: 'bag you desire', chance: 'rare' },
      { name: 'spectral saddle', chance: 'very rare' },
      { name: 'spectral horseshoe', chance: 'very rare' },
    ],
  },
];
