export const TIBIA_FANDOM_BATCH_4 = [
  {
    name: 'Mazoran',
    slug: 'Mazoran',
    imageUrl: 'https://static.tibia.com/images/library/creatures/mazoran.gif',
    boss: true,
    shortDescription:
      "Demoniczny boss z Ferumbras' Ascension, ktory sam w sobie jest prosty, ale arena regularnie zamienia sie w lawe. Najwieksze zagrozenie to obrazenia fire z podlogi i dodatkowe przywolania podczas kolejnych fal.",
    accessQuest: "Wymagany dostep do Ferumbras' Ascension Quest i wejscie do Grounds of Fire.",
    location: "Grounds of Fire, obszar Ferumbras' Ascension Quest.",
    soloLevel: '600+',
    groupLevel: '300+',
    attackStyle: [
      'mocne uderzenia fizyczne',
      'zalewanie areny lawa',
      'obrazenia fire z podlogi',
      'przywolania Rage of Mazoran',
    ],
    resistances: {
      physical: 0,
      earth: -75,
      fire: -100,
      ice: 0,
      energy: -75,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'Silver Token', chance: 'very common' },
      { name: 'Gold Coin', chance: 'common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Maimer', chance: 'uncommon' },
      { name: 'Wand of Everblazing', chance: 'semi-rare' },
      { name: 'Impaler of the Igniter', chance: 'rare' },
      { name: 'Tempest Shield', chance: 'very rare' },
    ],
  },
  {
    name: 'Mazzinor',
    slug: 'Mazzinor',
    imageUrl: 'https://static.tibia.com/images/library/creatures/mazzinor.gif',
    boss: true,
    shortDescription:
      'Biblioteczny demon energy, ktory co pewien czas przechodzi w faze niesmiertelnosci i przygotowuje zabojcze eksplozje na cala komnate. Kluczowe jest tworzenie vortexow z Wild Knowledge i wejscie w nie we wlasciwym momencie.',
    accessQuest:
      'Walka w ramach The Secret Library Quest; druzyna musi dotrzec do Earth Section i aktywowac Ostentatious Bookstand.',
    location: 'The Secret Library, sekcja Earth Section.',
    soloLevel: '950+',
    groupLevel: '500+',
    attackStyle: [
      'obrazenia energy z beamow i chainow',
      'faza niesmiertelnosci',
      'pelnopokojowe eksplozje energy',
      'przywolania Wild Knowledge',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: -100,
      ice: 0,
      energy: -75,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'Platinum Coin', chance: 'very common' },
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'Silver Token', chance: 'common' },
      { name: 'Ultimate Mana Potion', chance: 'common' },
      { name: 'Knowledgeable Book', chance: 'uncommon' },
      { name: 'Lightning Robe', chance: 'uncommon' },
      { name: 'Frozen Lightning', chance: 'rare' },
      { name: 'Energized Demonbone', chance: 'rare' },
    ],
  },
  {
    name: 'Megasylvan Yselda',
    slug: 'Megasylvan-Yselda',
    imageUrl: 'https://static.tibia.com/images/library/creatures/yselda.gif',
    boss: true,
    shortDescription:
      'Stacjonarny boss z Adventures of Galthen Quest, ktorego trzeba najpierw oslabic wypowiadajac konkretne slowa. Do pelnego zaliczenia walki warto dodatkowo utrzymac przy zyciu cztery Megasylvan Saplings w rogach sali.',
    accessQuest:
      'Wymagany postep w Adventures of Galthen Quest; do pelnego zaliczenia walki trzeba tez uleczyc cztery Megasylvan Saplings.',
    location: 'Forest of Life, przez Sleeping Carnisylvan.',
    soloLevel: '250+',
    groupLevel: '180+',
    attackStyle: [
      'uderzenia fizyczne',
      'przywolania Carnisylvan Sapling',
      'mechanika aktywacji haslem',
      'presja na leczenie sadzonek',
    ],
    resistances: {
      physical: -75,
      earth: -75,
      fire: -75,
      ice: -75,
      energy: -75,
      holy: 0,
      death: -75,
    },
    loot: [
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Ultimate Mana Potion', chance: 'common' },
      { name: 'Mastermind Potion', chance: 'common' },
      { name: 'Terra Mantle', chance: 'uncommon' },
      { name: 'Old Royal Diary', chance: 'uncommon' },
      { name: 'Megasylvan Sapling', chance: 'rare' },
    ],
  },
  {
    name: 'Melting Frozen Horror',
    slug: 'Melting-Frozen-Horror',
    imageUrl: 'https://static.tibia.com/images/library/creatures/frozenhorror.gif',
    boss: true,
    shortDescription:
      'Lodowy boss z Forgotten Knowledge, ktory leczy sie od obrazen ice i wymusza gre wokol Dragon Egg. Druzyna musi utrzymac bossa z dala od jajka i kontrolowac przywolane Frozen Miniony, bo ich ataki rowniez go wzmacniaja.',
    accessQuest:
      'Boss z Forgotten Knowledge Quest; trzeba wejsc do komnaty w Formorgar Mines i obsluzyc mechanike z Dragon Egg.',
    location: 'Formorgar Mines.',
    soloLevel: '500+',
    groupLevel: '180+',
    attackStyle: [
      'mocne uderzenia fizyczne',
      'leczenie od obrazen ice',
      'presja wokol Dragon Egg',
      'wsparcie Frozen Minionow',
    ],
    resistances: {
      physical: -75,
      earth: 0,
      fire: 25,
      ice: -100,
      energy: 25,
      holy: 0,
      death: 25,
    },
    loot: [
      { name: 'Frosty Heart', chance: 'very common' },
      { name: 'Spark Sphere', chance: 'very common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Crystalline Arrow', chance: 'common' },
      { name: 'Runic Ice Shield', chance: 'uncommon' },
      { name: 'Ornate Crossbow', chance: 'rare' },
      { name: 'Glowing Carrot', chance: 'rare' },
    ],
  },
  {
    name: 'Mimar Haffar',
    slug: 'Mimar-Haffar',
    imageUrl: 'https://static.tibia.com/images/library/creatures/mimarhaffar.gif',
    boss: true,
    shortDescription:
      'Pierwsza forma Mimar Haffar z Make Believe Quest i zarazem walka podpieta pod Boss Difficulty System. Strona wiki jest uboga, ale sam encounter nalezy traktowac jako nowoczesnego questa-bossa z rosnaca presja zalezne od wybranego poziomu trudnosci.',
    accessQuest:
      'Walka podczas Make Believe Quest w Moonstone Crater; dostep i nagrody zaleza od ustawien Boss Difficulty System.',
    location: 'Moonstone Crater.',
    soloLevel: '900+',
    groupLevel: '500+',
    attackStyle: [
      'presja pierwszej fazy',
      'atak bossa questowego',
      'mechaniki zalezne od poziomu trudnosci',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'Dirty Turban', chance: 'common' },
      { name: 'Moonsilver Battle Visor', chance: 'uncommon' },
      { name: 'Moonsilver Spirit Mask', chance: 'uncommon' },
      { name: 'Figurine of Mimar Haffar', chance: 'rare' },
    ],
  },
  {
    name: 'Mitmah Vanguard',
    slug: 'Mitmah-Vanguard',
    imageUrl: 'https://static.tibia.com/images/library/creatures/mitmahvanguard.gif',
    boss: true,
    shortDescription:
      'Bardzo niebezpieczny boss Iksupan, ktory teleportuje sie, rootuje cala druzyne i karze stanie blisko poteznym energy UE. Walka wymaga dystansu, bo potrafi tez przebijac magic wall i wild growth.',
    accessQuest:
      'Dostep przez Iksupan Occupied Sanctuary; pierwsze zabicie daje Museum Goer i drugi addon Ancient Aucar Outfits.',
    location: 'Iksupan Occupied Sanctuary.',
    soloLevel: '650+',
    groupLevel: '350+',
    attackStyle: [
      'ciosy w zwarciu',
      'energy UE i energy beam',
      'pelnoekranowy root',
      'fire wave oraz death ring',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: -75,
      ice: -75,
      energy: 0,
      holy: 0,
      death: -75,
    },
    loot: [
      { name: 'Crystal of the Mitmah', chance: 'common' },
      { name: 'Iks Footwraps', chance: 'uncommon' },
      { name: 'Stoic Iks Boots', chance: 'uncommon' },
      { name: 'Stoic Iks Casque', chance: 'uncommon' },
      { name: 'Stoic Iks Chestplate', chance: 'uncommon' },
      { name: 'Stoic Iks Robe', chance: 'uncommon' },
    ],
  },
  {
    name: 'Murcion',
    slug: 'Murcion',
    imageUrl: 'https://static.tibia.com/images/library/creatures/murcion.gif',
    boss: true,
    shortDescription:
      'Jeden z trudniejszych bossow Rotten Blood Quest, zostawiajacy mould zadajacy procentowe obrazenia i leczacy go, gdy sam na nim stoi. Dodatkowa presje robia wybuchajace Mushrooms oraz Elder Bloodjawy, przez co walka wymaga bardzo zdyscyplinowanego ruchu po malej sali.',
    accessQuest: 'Jeden z bossow Rotten Blood Quest, dostepny po wejsciu do Jaded Roots.',
    location: 'Jaded Roots.',
    soloLevel: '1000+',
    groupLevel: '600+',
    attackStyle: [
      'obrazenia death i agony',
      'mould z procentowymi obrazeniami',
      'wybuchajace Mushrooms z life drain',
      'przywolania Elder Bloodjaw',
    ],
    resistances: {
      physical: 0,
      earth: -75,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'Supreme Health Potion', chance: 'common' },
      { name: 'Ultimate Mana Potion', chance: 'common' },
      { name: 'Ultimate Spirit Potion', chance: 'common' },
      { name: 'The Essence of Murcion', chance: 'uncommon' },
      { name: 'Putrefactive Figurine', chance: 'uncommon' },
      { name: 'Spiritual Horseshoe', chance: 'rare' },
      { name: 'Bag You Covet', chance: 'very rare' },
    ],
  },
  {
    name: 'Neferi The Spy',
    slug: 'Neferi-The-Spy',
    imageUrl: 'https://static.tibia.com/images/library/creatures/neferithespy.gif',
    boss: true,
    shortDescription:
      'Miniboss z Kilmaresh, stawiajacy glownie na zwarcie, death damage i pojedyncze przywolanie Skeleton Elite Warrior. To raczej szybka walka, ale warto uwazac na nagle skoki obrazen oraz slabosc na ice.',
    accessQuest:
      'Miniboss Wanted mission z Kilmaresh Quest; wejscie przez teleport przy lodzi w Issavi.',
    location: 'Teleport przy lodzi w Issavi prowadzi do komnaty bossa.',
    soloLevel: '300+',
    groupLevel: '180+',
    attackStyle: [
      'mocne uderzenia fizyczne',
      'obrazenia death',
      'przywolania Skeleton Elite Warrior',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 25,
      energy: 0,
      holy: 0,
      death: -75,
    },
    loot: [
      { name: 'Crystal Coin', chance: 'common' },
      { name: 'Ultimate Health Potion', chance: 'common' },
      { name: 'Great Spirit Potion', chance: 'common' },
      { name: 'Eye-Embroidered Veil', chance: 'uncommon' },
      { name: 'Tagralt-Inlaid Scabbard', chance: 'uncommon' },
      { name: 'Stealth Ring', chance: 'uncommon' },
      { name: 'Golden Mask', chance: 'uncommon' },
      { name: 'Sea Horse Figurine', chance: 'rare' },
    ],
  },
  {
    name: 'Outburst',
    slug: 'Outburst',
    imageUrl: 'https://static.tibia.com/images/library/creatures/outburst.gif',
    boss: true,
    shortDescription:
      'Elektro-elementalny boss z Otherworld, ktory po przyjeciu obrazen kilkukrotnie przechodzi w forme Charging Outburst. Sama walka jest prostsza od bardziej technicznych encounterow, ale transformacje i obrazenia energy nadal potrafia zabolec slabsze postacie.',
    accessQuest:
      'Boss Heart of Destruction Quest w Otherworld; wymaga odblokowania odpowiedniej komnaty bossa.',
    location: 'Otherworld.',
    soloLevel: '500+',
    groupLevel: '250+',
    attackStyle: [
      'ciosy w zwarciu',
      'fazy Charging Outburst',
      'obrazenia energy',
      'presja pojedynczego celu',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 25,
      ice: 0,
      energy: 25,
      holy: 0,
      death: -75,
    },
    loot: [
      { name: 'Gold Token', chance: 'very common' },
      { name: 'Gold Coin', chance: 'common' },
      { name: 'Great Mana Potion', chance: 'common' },
      { name: 'Instable Proto Matter', chance: 'uncommon' },
      { name: 'Energy Ball', chance: 'uncommon' },
      { name: 'Void Boots', chance: 'rare' },
      { name: 'Tiara of Power', chance: 'rare' },
      { name: 'Lightning Robe', chance: 'rare' },
    ],
  },
  {
    name: 'Plagirath',
    slug: 'Plagirath',
    imageUrl: 'https://static.tibia.com/images/library/creatures/plagirath.gif',
    boss: true,
    shortDescription:
      "Plagowy demon z Ferumbras' Ascension, ktory zasypuje sale Oozami, paraliza i mocnym poison damage. Dodatkowo czasami przemienia cel w Bog Raider, a po zakonczeniu efektu nastepuje bolesna eksplozja wokol gracza.",
    accessQuest: "Wymagany dostep do Ferumbras' Ascension Quest i wejscie do Grounds of Plague.",
    location: "Grounds of Plague, obszar Ferumbras' Ascension Quest.",
    soloLevel: '750+',
    groupLevel: '350+',
    attackStyle: [
      'mocne uderzenia fizyczne',
      'poison UE, beam i wave',
      'death explosion',
      'transformacja celu w Bog Raider',
    ],
    resistances: {
      physical: 0,
      earth: -100,
      fire: 25,
      ice: -75,
      energy: 25,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'Silver Token', chance: 'very common' },
      { name: 'Gold Coin', chance: 'common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Great Mana Potion', chance: 'common' },
      { name: 'Plague Bite', chance: 'uncommon' },
      { name: 'Terra Legs', chance: 'uncommon' },
      { name: 'Muck Rod', chance: 'uncommon' },
      { name: 'Traditional Sai', chance: 'rare' },
    ],
  },
  {
    name: 'Ragiaz',
    slug: 'Ragiaz',
    imageUrl: 'https://static.tibia.com/images/library/creatures/ragiaz.gif',
    boss: true,
    shortDescription:
      'Nieumarlo-demoniczny boss z Grounds of Undeath, ktory miesza mocne ciosy fizyczne z earth damage i leczeniem. Najwazniejsza mechanika to szybkie zbicie Bone Capsule, bo w tej formie odzyskuje sporo zycia.',
    accessQuest: "Wymagany dostep do Ferumbras' Ascension Quest i wejscie do Grounds of Undeath.",
    location: "Grounds of Undeath, obszar Ferumbras' Ascension Quest.",
    soloLevel: '650+',
    groupLevel: '320+',
    attackStyle: [
      'mocne uderzenia fizyczne',
      'obrazenia earth',
      'samoleczenie przez Bone Capsule',
      'przywolania Death Dragon',
    ],
    resistances: {
      physical: 0,
      earth: -75,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: -75,
    },
    loot: [
      { name: 'Silver Token', chance: 'very common' },
      { name: 'Gold Coin', chance: 'common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Great Spirit Potion', chance: 'common' },
      { name: 'Death Gaze', chance: 'uncommon' },
      { name: 'Death Ring', chance: 'uncommon' },
      { name: "Reaper's Axe", chance: 'rare' },
      { name: 'Skull Staff', chance: 'rare' },
    ],
  },
  {
    name: 'Ratmiral Blackwhiskers',
    slug: 'Ratmiral-Blackwhiskers',
    imageUrl: 'https://static.tibia.com/images/library/creatures/ratmiral.gif',
    boss: true,
    shortDescription:
      "Finalny boss A Pirate's Tail Quest, walczacy w zwarciu, ale wspierany przez cala piracko-szczurza zaloge. Sama postac Ratmirala nie jest najgorsza, lecz dodatkowe Piraty i minibossowie szybko podnosza presje na druzyne.",
    accessQuest: "Finalny boss A Pirate's Tail Quest, walka w The Wreckoning.",
    location: 'The Wreckoning.',
    soloLevel: '400+',
    groupLevel: '220+',
    attackStyle: [
      'ciosy w zwarciu',
      'presja life drain od zalogi',
      'przywolania Elite Piratow i minibossow',
      'walka single-target z dodatkiem AoE',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'Pirate Coin', chance: 'common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Crystal Coin', chance: 'common' },
      { name: "Ratmiral's Hat", chance: 'semi-rare' },
      { name: 'Golden Cheese Wedge', chance: 'semi-rare' },
      { name: 'Cheesy Membership Card', chance: 'rare' },
      { name: 'Small Treasure Chest', chance: 'rare' },
      { name: 'Make-Do Boots', chance: 'very rare' },
    ],
  },
  {
    name: 'Ravenous Hunger',
    slug: 'Ravenous-Hunger',
    imageUrl: 'https://static.tibia.com/images/library/creatures/ravenoushunger.gif',
    boss: true,
    shortDescription:
      'Popularny daily boss z Cults of Tibia, glownie przez szanse na Elven Mail. Walczy w zwarciu, przywoluje Mutated Bats i leczy sie life drain wave, dlatego magowie powinni trzymac bezpieczny dystans.',
    accessQuest:
      "Boss z Cults of Tibia Quest, odblokowywany po dostepie do kryjowki pod jaskinia trolli w Ab'Dendriel.",
    location: "Pod trollowa jaskinia w Ab'Dendriel.",
    soloLevel: '450+',
    groupLevel: '250+',
    attackStyle: [
      'ciosy w zwarciu',
      'fala life drain',
      'przywolania Mutated Bat',
      'kontrola pola Fire Bomb Rune',
    ],
    resistances: {
      physical: 0,
      earth: -100,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: -100,
    },
    loot: [
      { name: 'Mysterious Remains', chance: 'very common' },
      { name: 'Gold Coin', chance: 'common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Sacred Tree Amulet', chance: 'uncommon' },
      { name: 'Terra Boots', chance: 'uncommon' },
      { name: 'Cobra Crown', chance: 'rare' },
      { name: 'Elven Mail', chance: 'rare' },
      { name: 'Enchanted Merudri Brooch', chance: 'very rare' },
    ],
  },
  {
    name: 'Razzagorn',
    slug: 'Razzagorn',
    imageUrl: 'https://static.tibia.com/images/library/creatures/razzargorn.gif',
    boss: true,
    shortDescription:
      "Destrukcyjny demon z Ferumbras' Ascension, mieszajacy fire, energy i death damage z przywolaniami Eruption of Destruction. Gdy addy zostana zignorowane, boss staje sie wyraznie grozniejszy i walka szybko sie destabilizuje.",
    accessQuest:
      "Wymagany dostep do Ferumbras' Ascension Quest i wejscie do Grounds of Destruction.",
    location: "Grounds of Destruction, obszar Ferumbras' Ascension Quest.",
    soloLevel: '700+',
    groupLevel: '350+',
    attackStyle: [
      'uderzenia fizyczne',
      'death beam',
      'fire wave i eksplozje',
      'przywolania Eruption of Destruction',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: -75,
      ice: 0,
      energy: 0,
      holy: -75,
      death: 0,
    },
    loot: [
      { name: 'Silver Token', chance: 'very common' },
      { name: 'Gold Coin', chance: 'common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Great Shield', chance: 'uncommon' },
      { name: 'Maimer', chance: 'uncommon' },
      { name: 'Visage of the End Days', chance: 'rare' },
      { name: 'Rift Crossbow', chance: 'rare' },
      { name: 'Orichalcum Pearl', chance: 'rare' },
    ],
  },
  {
    name: 'Realityquake',
    slug: 'Realityquake',
    imageUrl: 'https://static.tibia.com/images/library/creatures/realityquake.gif',
    boss: true,
    shortDescription:
      'Boss z Heart of Destruction pojawiajacy sie dopiero po pokonaniu Foreshock i Aftershock. Sama strona wiki podaje malo detali, ale encounter pelni role finalnego stat-checku tej sekwencji w Otherworld.',
    accessQuest:
      'Boss Heart of Destruction Quest; pojawia sie po pokonaniu Foreshock i Aftershock.',
    location: 'Otherworld.',
    soloLevel: '450+',
    groupLevel: '250+',
    attackStyle: ['ciosy fizyczne', 'presja energy', 'finalna faza po Foreshock i Aftershock'],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'Gold Token', chance: 'very common' },
      { name: 'Gold Coin', chance: 'common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Crystallized Anger', chance: 'uncommon' },
      { name: 'Energy Vein', chance: 'uncommon' },
      { name: 'Void Boots', chance: 'rare' },
      { name: 'Tiara of Power', chance: 'rare' },
      { name: 'Golden Legs', chance: 'very rare' },
    ],
  },
  {
    name: 'Rupture',
    slug: 'Rupture',
    imageUrl: 'https://static.tibia.com/images/library/creatures/rupture.gif',
    boss: true,
    shortDescription:
      'Boss z Otherworld, ktorego nie wolno bezmyslnie bic przez cala walke. Po pojawieniu sie Damage Resonance trzeba natychmiast przerzucic obrazenia na przywolanie, bo kazdy hit w Rupture leczy go o tysiace punktow zycia.',
    accessQuest:
      'Boss Heart of Destruction Quest w Otherworld; po odblokowaniu odpowiedniej areny.',
    location: 'Otherworld.',
    soloLevel: '650+',
    groupLevel: '320+',
    attackStyle: [
      'uderzenia fizyczne',
      'great drown beam',
      'great energy wave',
      'przywolania Damage Resonance',
    ],
    resistances: {
      physical: 0,
      earth: 0,
      fire: 0,
      ice: 0,
      energy: 0,
      holy: 0,
      death: 0,
    },
    loot: [
      { name: 'Gold Token', chance: 'very common' },
      { name: 'Mysterious Remains', chance: 'very common' },
      { name: 'Gold Coin', chance: 'common' },
      { name: 'Platinum Coin', chance: 'common' },
      { name: 'Odd Organ', chance: 'uncommon' },
      { name: 'Plasma Pearls', chance: 'uncommon' },
      { name: 'Shadow Sceptre', chance: 'rare' },
      { name: 'Ruthless Axe', chance: 'rare' },
    ],
  },
];
